// frontend/components/PlaybookExecutorStream.tsx
/*
 * Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
 * SPDX-License-Identifier: Apache-2.0
 */

"use client"

import { useState, useEffect, useRef, forwardRef, useImperativeHandle } from "react"
import {
  TkDialog,
  TkDialogRoot,
  TkDialogContent,
  TkDialogFooter,
  TkDialogHeader,
  TkDialogTitle
} from "thinkube-style/components/modals-overlays"
import { TkButton } from "thinkube-style/components/buttons-badges"
import { TkBadge } from "thinkube-style/components/buttons-badges"
import { TkCheckbox } from "thinkube-style/components/forms-inputs"
import { TkLabel } from "thinkube-style/components/forms-inputs"
import { Check, Loader2, Copy, Info, XCircle } from "lucide-react"
import { getAnsibleLogClassName, getAnsibleLogPrefix } from "@/lib/ansible-log-utils"
import { useCopyToClipboard } from "@/lib/use-copy-to-clipboard"

interface PlaybookExecutorProps {
  title: string
  playbookName: string
  testMode?: boolean
  onRetry?: () => void
  onComplete?: (result: any) => void
  playbookQueue?: Array<{ id: string; title: string; name: string; phase: string }>
  currentPlaybookIndex?: number
  onContinue?: () => void
  onTestPlaybook?: () => void
  onRollback?: () => void
  extraVars?: Record<string, any>
}

interface LogEntry {
  type: 'start' | 'play' | 'task' | 'ok' | 'changed' | 'failed' | 'output' | 'error' | 'complete' | 'skipped'
  message: string
  task?: string
  task_number?: number
}

interface TaskSummary {
  total: number
  ok: number
  changed: number
  skipped: number
  failed: number
}

export interface PlaybookExecutorRef {
  startExecution: (params: any) => void
  completeExecution: (result: any) => void
  cancelExecution: () => void
}

export const PlaybookExecutorStream = forwardRef<PlaybookExecutorRef, PlaybookExecutorProps>(
  (
    {
      title,
      playbookName,
      testMode = false,
      onRetry,
      onComplete,
      playbookQueue = [],
      currentPlaybookIndex = 0,
      onContinue,
      onTestPlaybook,
      onRollback,
      extraVars
    },
    ref
  ) => {
    // Reactive state
    const [isExecuting, setIsExecuting] = useState(false)
    const [showResult, setShowResult] = useState(false)
    const [status, setStatus] = useState<'pending' | 'running' | 'success' | 'error' | 'cancelled'>('pending')
    const [message, setMessage] = useState('')
    const [currentTask, setCurrentTask] = useState('')
    const [taskCount, setTaskCount] = useState(0)
    const [duration, setDuration] = useState<number | null>(null)
    const [isCancelling, setIsCancelling] = useState(false)
    const [logOutput, setLogOutput] = useState<LogEntry[]>([])
    const logContainerRef = useRef<HTMLDivElement>(null)
    const [autoScroll, setAutoScroll] = useState(true)
    const websocketRef = useRef<WebSocket | null>(null)
    const startTimeRef = useRef<number>(0)

    // Task summary - track unique tasks rather than host executions
    const [taskSummary, setTaskSummary] = useState<TaskSummary>({
      total: 0,
      ok: 0,
      changed: 0,
      skipped: 0,
      failed: 0
    })
    const seenTasksRef = useRef(new Set<string>())

    // Helper function for duration formatting
    const formatDuration = (seconds: number): string => {
      if (seconds < 60) {
        return `${seconds.toFixed(1)} seconds`
      } else {
        const minutes = Math.floor(seconds / 60)
        const remainingSeconds = Math.floor(seconds % 60)
        return `${minutes}m ${remainingSeconds}s`
      }
    }

    // Copy to clipboard
    const fullText = `Thinkube Installer - Playbook Execution Log
=====================================
Playbook: ${playbookName}
Title: ${title}
Status: ${status}
Duration: ${duration ? formatDuration(duration) : 'N/A'}
Tasks: Total ${taskSummary.total}, OK ${taskSummary.ok}, Changed ${taskSummary.changed}, Failed ${taskSummary.failed}
Timestamp: ${new Date().toISOString()}
=====================================

${logOutput.map(log => log.message).join('\n')}`

    const { copy, copied } = useCopyToClipboard(fullText)

    // Methods
    const startExecution = (params: any = {}) => {
      setIsExecuting(true)
      setShowResult(false)
      setStatus('running')
      setMessage('')
      setCurrentTask('Connecting...')
      setTaskCount(0)
      setDuration(null)
      setIsCancelling(false)
      setLogOutput([])
      setTaskSummary({ total: 0, ok: 0, changed: 0, skipped: 0, failed: 0 })
      seenTasksRef.current = new Set()
      startTimeRef.current = Date.now()

      // Connect WebSocket
      connectWebSocket(params)
    }

    const connectWebSocket = async (params: any) => {
      const encodedPlaybookName = encodeURIComponent(playbookName)

      // In Tauri, we need to connect directly to localhost:8000
      const isTauri = typeof window !== 'undefined' && window.location.protocol === 'tauri:'
      const wsBase =
        isTauri ||
        (typeof window !== 'undefined' &&
          window.location.protocol === 'http:' &&
          window.location.hostname === 'localhost')
          ? 'ws://localhost:8000'
          : typeof window !== 'undefined'
          ? `${window.location.protocol === 'https:' ? 'wss:' : 'ws:'}//${window.location.host}`
          : 'ws://localhost:8000'

      const wsUrl = `${wsBase}/ws/playbook/${encodedPlaybookName}`

      try {
        const ws = new WebSocket(wsUrl)
        websocketRef.current = ws

        // Store params in closure to ensure they're available in onopen
        const paramsToSend = params

        ws.onopen = async () => {
          let inventoryYAML = ''

          // Check if this is SSH-related playbook - use minimal inventory
          if (playbookName === 'setup-ssh-keys' || playbookName === 'test-ssh-connectivity') {
            // Dynamically import minimal inventory
            const { generateMinimalInventory, minimalInventoryToYAML } = await import(
              '../utils/minimalInventory.js'
            )
            const minimalInventory = generateMinimalInventory()
            inventoryYAML = minimalInventoryToYAML(minimalInventory)
          } else {
            // Use full inventory for other playbooks
            const { generateDynamicInventory, inventoryToYAML } = await import(
              '../utils/inventoryGenerator.js'
            )
            const dynamicInventory = generateDynamicInventory()
            inventoryYAML = inventoryToYAML(dynamicInventory)
          }

          // Add inventory to parameters
          const paramsWithInventory = {
            ...paramsToSend,
            inventory: inventoryYAML
          }

          // Add ZeroTier-specific environment variables if this is a ZeroTier playbook
          if (playbookName.includes('zerotier')) {
            const zerotierApiToken = sessionStorage.getItem('zerotierApiToken')
            const zerotierNetworkId = sessionStorage.getItem('zerotierNetworkId')

            if (zerotierApiToken || zerotierNetworkId) {
              paramsWithInventory.environment = {
                ...paramsWithInventory.environment
              }

              if (zerotierApiToken) {
                paramsWithInventory.environment.ZEROTIER_API_TOKEN = zerotierApiToken
              }
              if (zerotierNetworkId) {
                paramsWithInventory.environment.ZEROTIER_NETWORK_ID = zerotierNetworkId
              }
            }
          }

          // Add Cloudflare token if needed
          if (playbookName.includes('cert-manager') || playbookName.includes('dns')) {
            const cloudflareToken = sessionStorage.getItem('cloudflareToken')
            if (cloudflareToken) {
              paramsWithInventory.environment = {
                ...paramsWithInventory.environment,
                CLOUDFLARE_TOKEN: cloudflareToken
              }
            }
          }

          // Add GitHub token if needed
          if (playbookName.includes('github') || playbookName.includes('devpi')) {
            const githubToken = sessionStorage.getItem('githubToken')
            if (githubToken) {
              paramsWithInventory.environment = {
                ...paramsWithInventory.environment,
                GITHUB_TOKEN: githubToken
              }
            }
          }

          // Send execution parameters with dynamic inventory
          try {
            if (ws && ws.readyState === WebSocket.OPEN) {
              ws.send(JSON.stringify(paramsWithInventory))
            } else {
              setLogOutput((prev) => [
                ...prev,
                {
                  type: 'error',
                  message: 'WebSocket not ready - connection may have failed'
                }
              ])
            }
          } catch (error) {
            setLogOutput((prev) => [
              ...prev,
              {
                type: 'error',
                message: `Failed to send parameters: ${error}`
              }
            ])
          }
        }

        ws.onmessage = (event) => {
          const data = JSON.parse(event.data)
          handleWebSocketMessage(data)
        }

        ws.onerror = (error) => {
          setLogOutput((prev) => [
            ...prev,
            {
              type: 'error',
              message: 'Connection error occurred'
            }
          ])
        }

        ws.onclose = () => {
          if (status === 'running') {
            setStatus('error')
            setMessage('Connection lost')
            completeExecution({
              status: 'error',
              message: 'Connection to server lost'
            })
          }
        }
      } catch (error) {
        setLogOutput((prev) => [
          ...prev,
          {
            type: 'error',
            message: `Failed to connect: ${error}`
          }
        ])
        completeExecution({
          status: 'error',
          message: 'Failed to establish connection'
        })
      }
    }

    const handleWebSocketMessage = (data: any) => {
      // Add to log
      setLogOutput((prev) => [
        ...prev,
        {
          type: data.type,
          message: data.message,
          task: data.task,
          task_number: data.task_number
        }
      ])

      // Handle different message types
      switch (data.type) {
        case 'start':
          setCurrentTask('Starting playbook execution...')
          break

        case 'task':
          setCurrentTask(data.task_name)
          setTaskCount(data.task_number)

          // Track unique tasks only
          if (data.task_name && !seenTasksRef.current.has(data.task_name)) {
            seenTasksRef.current.add(data.task_name)
            setTaskSummary((prev) => ({ ...prev, total: prev.total + 1 }))
          }
          break

        case 'ok':
          // Count ok tasks separately (not changed)
          if (data.task && !seenTasksRef.current.has(data.task + '_ok')) {
            seenTasksRef.current.add(data.task + '_ok')
            setTaskSummary((prev) => ({ ...prev, ok: prev.ok + 1 }))
          }
          break

        case 'changed':
          // Count changed tasks separately
          if (data.task && !seenTasksRef.current.has(data.task + '_changed')) {
            seenTasksRef.current.add(data.task + '_changed')
            setTaskSummary((prev) => ({ ...prev, changed: prev.changed + 1 }))
          }
          break

        case 'skipped':
          // Count skipped tasks
          if (data.task && !seenTasksRef.current.has(data.task + '_skipped')) {
            seenTasksRef.current.add(data.task + '_skipped')
            setTaskSummary((prev) => ({ ...prev, skipped: prev.skipped + 1 }))
          }
          break

        case 'failed':
          // Mark task as failed
          if (data.task && !seenTasksRef.current.has(data.task + '_failed')) {
            seenTasksRef.current.add(data.task + '_failed')
            setTaskSummary((prev) => ({ ...prev, failed: prev.failed + 1 }))
          }
          break

        case 'complete':
          const executionDuration = (Date.now() - startTimeRef.current) / 1000
          setDuration(executionDuration)
          setStatus(data.status)
          setMessage(data.message)
          completeExecution({
            status: data.status,
            message: data.message,
            duration: executionDuration
          })
          break

        case 'error':
          setStatus('error')
          setMessage(data.message)
          break
      }
    }

    const completeExecution = (result: any) => {
      setIsExecuting(false)
      setShowResult(true)
      websocketRef.current?.close()
      websocketRef.current = null

      // Call onComplete prop if provided
      if (onComplete) {
        onComplete(result)
      }

      // Auto-continue on success after a short delay (unless in test mode)
      if (result.status === 'success' && !testMode) {
        setTimeout(() => {
          // Only auto-continue if the modal is still showing (user hasn't manually closed it)
          if (showResult && status === 'success') {
            closeResult()
          }
        }, 3000) // 3 second delay to show success message
      }
    }

    const cancelExecution = () => {
      setIsCancelling(true)
      websocketRef.current?.close()
      setStatus('cancelled')
      setMessage('Execution was cancelled')
      setIsExecuting(false)
      setShowResult(true)
      setIsCancelling(false)

      // Call onComplete prop if provided
      const result = {
        status: 'cancelled',
        message: 'Execution was cancelled by user',
        duration
      }
      if (onComplete) {
        onComplete(result)
      }
    }

    const closeResult = () => {
      setShowResult(false)

      // Only emit continue if the playbook was successful
      if (status === 'success' && onContinue) {
        onContinue()
      }

      // Reset state
      setStatus('pending')
      setMessage('')
      setCurrentTask('')
      setTaskCount(0)
      setDuration(null)
      setLogOutput([])
      setTaskSummary({ total: 0, ok: 0, changed: 0, skipped: 0, failed: 0 })
      seenTasksRef.current = new Set()
    }

    const retry = () => {
      if (onRetry) {
        // Close the result modal without emitting continue
        setShowResult(false)

        // Reset state
        setStatus('pending')
        setMessage('')
        setCurrentTask('')
        setTaskCount(0)
        setDuration(null)
        setLogOutput([])
        setTaskSummary({ total: 0, ok: 0, changed: 0, skipped: 0, failed: 0 })
        seenTasksRef.current = new Set()

        // Call the retry handler
        onRetry()
      }
    }

    const getLogTypeFromMessage = (message: string): LogEntry['type'] => {
      if (message.includes('ERROR') || message.includes('failed')) return 'failed'
      if (message.includes('WARNING')) return 'error'
      if (message.includes('TASK')) return 'task'
      if (message.includes('PLAY')) return 'play'
      if (message.includes('ok:')) return 'ok'
      if (message.includes('changed:')) return 'changed'
      if (message.includes('skipped:')) return 'skipped'
      return 'output'
    }

    // Expose methods to parent component
    useImperativeHandle(ref, () => ({
      startExecution,
      completeExecution,
      cancelExecution
    }))

    // Auto-scroll effect
    useEffect(() => {
      if (autoScroll && logContainerRef.current) {
        logContainerRef.current.scrollTop = logContainerRef.current.scrollHeight
      }
    }, [logOutput, autoScroll])

    // Render compact playbook queue steps
    const renderPlaybookQueue = () => {
      if (!playbookQueue || playbookQueue.length === 0) return null

      return (
        <div className="mb-3 overflow-x-auto">
          <div className="flex gap-1 min-h-2">
            {playbookQueue.map((playbook, idx) => {
              const isCompleted = idx < currentPlaybookIndex
              const isCurrent = idx === currentPlaybookIndex
              const isPending = idx > currentPlaybookIndex

              return (
                <div
                  key={playbook.id}
                  className="group relative cursor-help"
                  title={playbook.title}
                >
                  <div
                    className={`w-2 h-2 rounded-full transition-all ${
                      isCompleted
                        ? 'bg-primary'
                        : isCurrent
                        ? 'bg-warning animate-pulse'
                        : 'bg-muted'
                    }`}
                  />
                </div>
              )
            })}
          </div>
        </div>
      )
    }

    return (
      <div className="playbook-executor">
        {/* Execution Modal */}
        <TkDialogRoot open={isExecuting} onOpenChange={() => {}}>
          <TkDialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
            {renderPlaybookQueue()}

            <TkDialogHeader>
              <TkDialogTitle>{title}</TkDialogTitle>
            </TkDialogHeader>

            {/* Task TkProgress */}
            {currentTask && (
              <div className="mb-4">
                <div className="flex justify-between text-sm mb-1">
                  <span className="font-semibold">{currentTask}</span>
                  {taskCount > 0 && (
                    <span className="text-sm text-muted-foreground">Task {taskCount}</span>
                  )}
                </div>
              </div>
            )}

            {/* Live Output Log */}
            <div className="mb-4">
              <div className="flex justify-between items-center mb-2">
                <span className="text-sm text-muted-foreground">Live Output:</span>
                <div className="flex items-center gap-2">
                  <TkButton
                    variant="ghost"
                    size="sm"
                    onClick={copy}
                    className={copied ? 'text-success' : ''}
                  >
                    {copied ? <Check className="w-4 h-4 mr-1" /> : <Copy className="w-4 h-4 mr-1" />}
                    {copied ? 'Copied!' : 'Copy'}
                  </TkButton>
                  <div className="flex items-center gap-2">
                    <TkCheckbox
                      id="auto-scroll-exec"
                      checked={autoScroll}
                      onCheckedChange={(checked: boolean) => setAutoScroll(checked as boolean)}
                    />
                    <TkLabel htmlFor="auto-scroll-exec" className="text-xs cursor-pointer">
                      Auto-scroll
                    </TkLabel>
                  </div>
                </div>
              </div>
              <div
                ref={logContainerRef}
                className="h-96 overflow-y-auto overflow-x-auto p-4 bg-muted/30 rounded-lg font-mono text-xs"
              >
                {logOutput.length === 0 && (
                  <div className="text-muted-foreground">
                    <div className="flex items-start">
                      <span className="mr-2 shrink-0">$</span>
                      <code className="break-all">Waiting for output...</code>
                    </div>
                  </div>
                )}
                {logOutput.map((log, idx) => {
                  const logType = log.type || getLogTypeFromMessage(log.message)
                  return (
                    <div key={idx} className={`flex items-start ${getAnsibleLogClassName(logType)}`}>
                      <span className="text-muted-foreground mr-2 shrink-0">
                        {getAnsibleLogPrefix(logType)}
                      </span>
                      <code className="break-all">{log.message}</code>
                    </div>
                  )
                })}
              </div>
            </div>

            {/* Status Summary */}
            {taskSummary.total > 0 && (
              <div className="grid grid-cols-5 gap-2 mb-4">
                <div className="text-center">
                  <div className="text-xs text-muted-foreground">Total</div>
                  <div className="text-lg font-bold">{taskSummary.total}</div>
                </div>
                {taskSummary.ok > 0 && (
                  <div className="text-center">
                    <div className="text-xs text-muted-foreground">OK</div>
                    <div className="text-lg font-bold text-success">{taskSummary.ok}</div>
                  </div>
                )}
                {taskSummary.changed > 0 && (
                  <div className="text-center">
                    <div className="text-xs text-muted-foreground">Changed</div>
                    <div className="text-lg font-bold text-warning">{taskSummary.changed}</div>
                  </div>
                )}
                {taskSummary.skipped > 0 && (
                  <div className="text-center">
                    <div className="text-xs text-muted-foreground">Skipped</div>
                    <div className="text-lg font-bold text-info">{taskSummary.skipped}</div>
                  </div>
                )}
                {taskSummary.failed > 0 && (
                  <div className="text-center">
                    <div className="text-xs text-muted-foreground">Failed</div>
                    <div className="text-lg font-bold text-destructive">{taskSummary.failed}</div>
                  </div>
                )}
              </div>
            )}

            {/* Cancel TkButton (only during execution) */}
            {status === 'running' && (
              <TkDialogFooter>
                <TkButton variant="outline" size="sm" onClick={cancelExecution} disabled={isCancelling}>
                  {isCancelling && <Loader2 className="w-4 h-4 mr-1 animate-spin" />}
                  {isCancelling ? 'Cancelling...' : 'Cancel'}
                </TkButton>
              </TkDialogFooter>
            )}
          </TkDialogContent>
        </TkDialogRoot>

        {/* Result Modal */}
        <TkDialogRoot open={showResult} onOpenChange={closeResult}>
          <TkDialogContent className="max-w-2xl">
            {renderPlaybookQueue()}

            <TkDialogHeader>
              <TkDialogTitle>{title} - Complete</TkDialogTitle>
            </TkDialogHeader>

            {/* Success Result */}
            {status === 'success' && (
              <div className="bg-success/10 border border-success text-success rounded-lg p-4 flex gap-3 mb-4">
                <Check className="h-6 w-6 shrink-0" />
                <div>
                  <span>{message || 'Playbook completed successfully'}</span>
                  <div className="text-sm mt-1 opacity-80">Continuing automatically in 3 seconds...</div>
                </div>
              </div>
            )}

            {/* Error Result */}
            {status === 'error' && (
              <>
                <div className="bg-destructive/10 border border-destructive text-destructive rounded-lg p-4 flex gap-3 mb-4">
                  <XCircle className="h-6 w-6 shrink-0" />
                  <span>{message || 'Playbook execution failed'}</span>
                </div>

                {/* GitHub Issue Helper */}
                <div className="bg-info/10 border border-info text-info rounded-lg p-4 flex gap-3 mb-4">
                  <Info className="h-6 w-6 shrink-0" />
                  <div>
                    <p className="font-semibold">Need help?</p>
                    <p className="text-sm">Copy the log output and create an issue on GitHub for assistance.</p>
                  </div>
                </div>
              </>
            )}

            {/* Final Summary */}
            {taskSummary.total > 0 && (
              <div className="mb-4">
                <p className="text-sm text-muted-foreground mb-2">Execution Summary:</p>
                <div className="text-sm">
                  <p>Total Tasks: {taskSummary.total}</p>
                  {taskSummary.ok > 0 && <p className="text-success">OK: {taskSummary.ok}</p>}
                  {taskSummary.changed > 0 && <p className="text-warning">Changed: {taskSummary.changed}</p>}
                  {taskSummary.skipped > 0 && <p className="text-info">Skipped: {taskSummary.skipped}</p>}
                  {taskSummary.failed > 0 && <p className="text-destructive">Failed: {taskSummary.failed}</p>}
                </div>
              </div>
            )}

            {/* Execution Time */}
            {duration && (
              <div className="mb-4">
                <div className="text-sm text-muted-foreground">Completed in {formatDuration(duration)}</div>
              </div>
            )}

            {/* Actions */}
            <TkDialogFooter>
              <TkButton variant="ghost" size="sm" onClick={copy} className={copied ? 'text-success' : ''}>
                {copied ? <Check className="w-4 h-4 mr-1" /> : <Copy className="w-4 h-4 mr-1" />}
                {copied ? 'Copied!' : 'Copy Log'}
              </TkButton>

              {/* Test Mode buttons - only show on success */}
              {testMode && status === 'success' && (
                <>
                  <TkButton
                    variant="outline"
                    size="sm"
                    className="bg-info text-info-foreground"
                    onClick={onTestPlaybook}
                  >
                    Run Test (18)
                  </TkButton>
                  <TkButton
                    variant="outline"
                    size="sm"
                    className="bg-warning text-warning-foreground"
                    onClick={onRollback}
                  >
                    Rollback (19)
                  </TkButton>
                </>
              )}

              <TkButton onClick={closeResult}>{status === 'success' ? 'Continue' : 'Close'}</TkButton>
              {status === 'error' && onRetry && (
                <TkButton variant="outline" onClick={retry}>
                  Retry
                </TkButton>
              )}
            </TkDialogFooter>
          </TkDialogContent>
        </TkDialogRoot>
      </div>
    )
  }
)

PlaybookExecutorStream.displayName = 'PlaybookExecutorStream'

// frontend/src/components/PlaybookExecutorStream.vue
/*
 * Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
 * SPDX-License-Identifier: Apache-2.0
 */

<template>
  <div class="playbook-executor">
    <!-- Execution Modal -->
    <div v-if="isExecuting" class="modal modal-open">
      <div class="modal-box max-w-4xl">
        <!-- Playbook Queue Steps (Compact) -->
        <div v-if="playbookQueue && playbookQueue.length > 0" class="mb-3 overflow-x-auto">
          <ul class="steps steps-horizontal w-full steps-compact">
            <li v-for="(playbook, idx) in playbookQueue"
                :key="playbook.id"
                class="step step-xs cursor-help"
                :class="{
                  'step-primary': idx < currentPlaybookIndex,
                  'step-warning': idx === currentPlaybookIndex,
                  'step-neutral': idx > currentPlaybookIndex
                }"
                :data-content="idx < currentPlaybookIndex ? '✓' : (idx === currentPlaybookIndex ? '●' : '')"
                :title="playbook.title">
            </li>
          </ul>
        </div>

        <h3 class="font-bold text-lg mb-4">{{ title }}</h3>
        
        <!-- Task Progress -->
        <div v-if="currentTask" class="mb-4">
          <div class="flex justify-between text-sm mb-1">
            <span class="font-semibold">{{ currentTask }}</span>
            <span v-if="taskCount > 0" class="text-sm text-base-content text-opacity-70">
              Task {{ taskCount }}
            </span>
          </div>
        </div>
        
        <!-- Live Output Log -->
        <div class="mb-4">
          <div class="flex justify-between items-center mb-2">
            <span class="text-sm text-gray-600">Live Output:</span>
            <div class="flex items-center gap-2">
              <button 
                class="btn btn-ghost btn-xs gap-1"
                @click="copyOutput"
                :class="{ 'btn-success': copySuccess }"
              >
                <svg v-if="!copySuccess" class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3"></path>
                </svg>
                <svg v-else class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
                </svg>
                {{ copySuccess ? 'Copied!' : 'Copy' }}
              </button>
              <label class="label cursor-pointer gap-2">
                <span class="label-text text-xs">Auto-scroll</span>
                <input type="checkbox" v-model="autoScroll" class="checkbox checkbox-xs" />
              </label>
            </div>
          </div>
          <div 
            class="mockup-code h-96 overflow-y-auto text-xs"
            ref="logContainer"
          >
            <div v-if="logOutput.length === 0" class="text-base-content text-opacity-50">
              <pre data-prefix="$"><code>Waiting for output...</code></pre>
            </div>
            <pre 
              v-for="(log, idx) in logOutput" 
              :key="idx"
              :data-prefix="getLogPrefix(log.type)"
              :class="getLogClass(log.type)"
            ><code>{{ log.message }}</code></pre>
          </div>
        </div>
        
        <!-- Status Summary -->
        <div v-if="taskSummary.total > 0" class="stats stats-horizontal w-full mb-4">
          <div class="stat place-items-center py-2">
            <div class="stat-title text-xs">Total</div>
            <div class="stat-value text-lg">{{ taskSummary.total }}</div>
          </div>
          <div v-if="taskSummary.ok > 0" class="stat place-items-center py-2">
            <div class="stat-title text-xs">OK</div>
            <div class="stat-value text-lg text-success">{{ taskSummary.ok }}</div>
          </div>
          <div v-if="taskSummary.changed > 0" class="stat place-items-center py-2">
            <div class="stat-title text-xs">Changed</div>
            <div class="stat-value text-lg text-warning">{{ taskSummary.changed }}</div>
          </div>
          <div v-if="taskSummary.skipped > 0" class="stat place-items-center py-2">
            <div class="stat-title text-xs">Skipped</div>
            <div class="stat-value text-lg text-info">{{ taskSummary.skipped }}</div>
          </div>
          <div v-if="taskSummary.failed > 0" class="stat place-items-center py-2">
            <div class="stat-title text-xs">Failed</div>
            <div class="stat-value text-lg text-error">{{ taskSummary.failed }}</div>
          </div>
        </div>
        
        <!-- Cancel Button (only during execution) -->
        <div v-if="status === 'running'" class="modal-action">
          <button class="btn btn-outline btn-sm" @click="cancelExecution" :disabled="isCancelling">
            <span v-if="isCancelling" class="loading loading-spinner loading-xs"></span>
            {{ isCancelling ? 'Cancelling...' : 'Cancel' }}
          </button>
        </div>
      </div>
      <form method="dialog" class="modal-backdrop">
        <button>close</button>
      </form>
    </div>

    <!-- Result Modal -->
    <div v-if="showResult" class="modal modal-open">
      <div class="modal-box max-w-2xl">
        <!-- Playbook Queue Steps (Compact) -->
        <div v-if="playbookQueue && playbookQueue.length > 0" class="mb-3 overflow-x-auto">
          <ul class="steps steps-horizontal w-full steps-compact">
            <li v-for="(playbook, idx) in playbookQueue"
                :key="playbook.id"
                class="step step-xs cursor-help"
                :class="{
                  'step-primary': idx < currentPlaybookIndex,
                  'step-warning': idx === currentPlaybookIndex,
                  'step-neutral': idx > currentPlaybookIndex
                }"
                :data-content="idx < currentPlaybookIndex ? '✓' : (idx === currentPlaybookIndex ? '●' : '')"
                :title="playbook.title">
            </li>
          </ul>
        </div>

        <h3 class="font-bold text-lg mb-4">{{ title }} - Complete</h3>
        
        <!-- Success Result -->
        <div v-if="status === 'success'" class="alert alert-success mb-4">
          <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <div>
            <span>{{ message || 'Playbook completed successfully' }}</span>
            <div class="text-sm mt-1 opacity-80">Continuing automatically in 3 seconds...</div>
          </div>
        </div>
        
        <!-- Error Result -->
        <div v-if="status === 'error'">
          <div class="alert alert-error mb-4">
            <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <span>{{ message || 'Playbook execution failed' }}</span>
          </div>
          
          <!-- GitHub Issue Helper -->
          <div class="alert alert-info mb-4">
            <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
            </svg>
            <div>
              <p class="font-semibold">Need help?</p>
              <p class="text-sm">Copy the log output and create an issue on GitHub for assistance.</p>
            </div>
          </div>
        </div>
        
        <!-- Final Summary -->
        <div v-if="taskSummary.total > 0" class="mb-4">
          <p class="text-sm text-gray-600 mb-2">Execution Summary:</p>
          <div class="text-sm">
            <p>Total Tasks: {{ taskSummary.total }}</p>
            <p v-if="taskSummary.ok > 0" class="text-success">OK: {{ taskSummary.ok }}</p>
            <p v-if="taskSummary.changed > 0" class="text-warning">Changed: {{ taskSummary.changed }}</p>
            <p v-if="taskSummary.skipped > 0" class="text-info">Skipped: {{ taskSummary.skipped }}</p>
            <p v-if="taskSummary.failed > 0" class="text-error">Failed: {{ taskSummary.failed }}</p>
          </div>
        </div>
        
        <!-- Execution Time -->
        <div v-if="duration" class="mb-4">
          <div class="text-sm text-gray-600">
            Completed in {{ formatDuration(duration) }}
          </div>
        </div>
        
        <!-- Actions -->
        <div class="modal-action">
          <button
            class="btn btn-ghost btn-sm gap-1"
            @click="copyOutput"
            :class="{ 'btn-success': copySuccess }"
          >
            <svg v-if="!copySuccess" class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3"></path>
            </svg>
            <svg v-else class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
            </svg>
            {{ copySuccess ? 'Copied!' : 'Copy Log' }}
          </button>

          <!-- Test Mode buttons - only show on success -->
          <template v-if="testMode && status === 'success'">
            <button class="btn btn-info btn-sm" @click="emitTestPlaybook">
              🧪 Run Test (18)
            </button>
            <button class="btn btn-warning btn-sm" @click="emitRollback">
              🔄 Rollback (19)
            </button>
          </template>

          <button class="btn btn-primary" @click="closeResult">
            {{ status === 'success' ? 'Continue' : 'Close' }}
          </button>
          <button v-if="status === 'error' && onRetry" class="btn btn-outline" @click="retry">
            Retry
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, nextTick } from 'vue'

interface PlaybookExecutorProps {
  title: string
  playbookName: string
  testMode?: boolean
  onRetry?: () => void
  onComplete?: (result: any) => void
  playbookQueue?: Array<{ id: string; title: string; name: string; phase: string }>
  currentPlaybookIndex?: number
}

interface LogEntry {
  type: 'start' | 'play' | 'task' | 'ok' | 'changed' | 'failed' | 'output' | 'error' | 'complete'
  message: string
  task?: string
  task_number?: number
}

const props = defineProps<PlaybookExecutorProps>()
const emit = defineEmits(['complete', 'continue', 'test-playbook', 'rollback'])

// Reactive state
const isExecuting = ref(false)
const showResult = ref(false)
const status = ref<'pending' | 'running' | 'success' | 'error' | 'cancelled'>('pending')
const message = ref('')
const currentTask = ref('')
const taskCount = ref(0)
const duration = ref<number | null>(null)
const isCancelling = ref(false)
const logOutput = ref<LogEntry[]>([])
const logContainer = ref<HTMLElement>()
const autoScroll = ref(true)
const websocket = ref<WebSocket | null>(null)
const startTime = ref<number>(0)
const copySuccess = ref(false)

// Task summary - track unique tasks rather than host executions
const taskSummary = ref({
  total: 0,
  ok: 0,
  changed: 0,
  skipped: 0,
  failed: 0
})
const seenTasks = ref(new Set())

// Methods
const startExecution = (params: any = {}) => {
  isExecuting.value = true
  showResult.value = false
  status.value = 'running'
  message.value = ''
  currentTask.value = 'Connecting...'
  taskCount.value = 0
  duration.value = null
  isCancelling.value = false
  logOutput.value = []
  taskSummary.value = { total: 0, ok: 0, changed: 0, skipped: 0, failed: 0 }
  seenTasks.value = new Set()
  startTime.value = Date.now()
  
  // Connect WebSocket
  connectWebSocket(params)
}

const connectWebSocket = (params: any) => {
  const encodedPlaybookName = encodeURIComponent(props.playbookName)

  // In Tauri, we need to connect directly to localhost:8000
  // Tauri v2 uses tauri: protocol, not window.__TAURI__
  const isTauri = window.location.protocol === 'tauri:'
  const wsBase = isTauri || (window.location.protocol === 'http:' && window.location.hostname === 'localhost')
    ? 'ws://localhost:8000'
    : `${window.location.protocol === 'https:' ? 'wss:' : 'ws:'}//${window.location.host}`
  
  const wsUrl = `${wsBase}/ws/playbook/${encodedPlaybookName}`
  console.log('Connecting to WebSocket URL:', wsUrl)
  
  try {
    websocket.value = new WebSocket(wsUrl)
    console.log('WebSocket created, setting up handlers...')
    
    // Store params in closure to ensure they're available in onopen
    const paramsToSend = params
    
    websocket.value.onopen = async () => {
      console.log('WebSocket onopen triggered, readyState:', websocket.value?.readyState)
    
    let inventoryYAML = ''
    
    // Check if this is SSH-related playbook - use minimal inventory
    if (props.playbookName === 'setup-ssh-keys' || props.playbookName === 'test-ssh-connectivity') {
      const { generateMinimalInventory, minimalInventoryToYAML } = await import('../utils/minimalInventory.js')
      const minimalInventory = generateMinimalInventory()
      inventoryYAML = minimalInventoryToYAML(minimalInventory)
    } else {
      // Use full inventory for other playbooks
      const { generateDynamicInventory, inventoryToYAML } = await import('../utils/inventoryGenerator.js')
      const dynamicInventory = generateDynamicInventory()
      inventoryYAML = inventoryToYAML(dynamicInventory)
    }
    
    // Add inventory to parameters
    const paramsWithInventory = {
      ...paramsToSend,
      inventory: inventoryYAML
    }
    
    // Add ZeroTier-specific environment variables if this is a ZeroTier playbook
    if (props.playbookName.includes('zerotier')) {
      const zerotierApiToken = sessionStorage.getItem('zerotierApiToken')
      const zerotierNetworkId = sessionStorage.getItem('zerotierNetworkId')
      
      if (zerotierApiToken || zerotierNetworkId) {
        paramsWithInventory.environment = {
          ...paramsWithInventory.environment
        }
        
        if (zerotierApiToken) {
          paramsWithInventory.environment.ZEROTIER_API_TOKEN = zerotierApiToken
        }
        if (zerotierNetworkId) {
          paramsWithInventory.environment.ZEROTIER_NETWORK_ID = zerotierNetworkId
        }
      }
    }
    
    // Add Cloudflare token if needed
    if (props.playbookName.includes('cert-manager') || props.playbookName.includes('dns')) {
      const cloudflareToken = sessionStorage.getItem('cloudflareToken')
      if (cloudflareToken) {
        paramsWithInventory.environment = {
          ...paramsWithInventory.environment,
          CLOUDFLARE_TOKEN: cloudflareToken
        }
      }
    }
    
    // Add GitHub token if needed
    if (props.playbookName.includes('github') || props.playbookName.includes('devpi')) {
      const githubToken = sessionStorage.getItem('githubToken')
      if (githubToken) {
        paramsWithInventory.environment = {
          ...paramsWithInventory.environment,
          GITHUB_TOKEN: githubToken
        }
      }
    }
    
    // Send execution parameters with dynamic inventory
    console.log('Preparing to send parameters...')
    console.log('WebSocket state:', websocket.value?.readyState, 'OPEN=', WebSocket.OPEN)
    console.log('Parameters to send:', paramsWithInventory)
    
    try {
      if (websocket.value && websocket.value.readyState === WebSocket.OPEN) {
        const jsonData = JSON.stringify(paramsWithInventory)
        console.log('Sending JSON data, length:', jsonData.length)
        websocket.value.send(jsonData)
        console.log('Parameters sent successfully')
      } else {
        console.error('WebSocket not ready to send. State:', websocket.value?.readyState, 'Expected:', WebSocket.OPEN)
        logOutput.value.push({
          type: 'error',
          message: 'WebSocket not ready - connection may have failed'
        })
      }
    } catch (error) {
      console.error('Error sending parameters:', error)
      logOutput.value.push({
        type: 'error',
        message: `Failed to send parameters: ${error}`
      })
    }
  }
  
  websocket.value.onmessage = (event) => {
    console.log('WebSocket message received:', event.data)
    const data = JSON.parse(event.data)
    handleWebSocketMessage(data)
  }
  
  websocket.value.onerror = (error) => {
    console.error('WebSocket error:', error)
    logOutput.value.push({
      type: 'error',
      message: 'Connection error occurred'
    })
  }
  
  websocket.value.onclose = () => {
    console.log('WebSocket disconnected')
    if (status.value === 'running') {
      status.value = 'error'
      message.value = 'Connection lost'
      completeExecution({
        status: 'error',
        message: 'Connection to server lost'
      })
    }
  }
  } catch (error) {
    console.error('Error creating WebSocket:', error)
    logOutput.value.push({
      type: 'error',
      message: `Failed to connect: ${error}`
    })
    completeExecution({
      status: 'error',
      message: 'Failed to establish connection'
    })
  }
}

const handleWebSocketMessage = (data: any) => {
  // Add to log
  logOutput.value.push({
    type: data.type,
    message: data.message,
    task: data.task,
    task_number: data.task_number
  })
  
  // Auto-scroll to bottom
  if (autoScroll.value) {
    nextTick(() => {
      if (logContainer.value) {
        logContainer.value.scrollTop = logContainer.value.scrollHeight
      }
    })
  }
  
  // Handle different message types
  switch (data.type) {
    case 'start':
      currentTask.value = 'Starting playbook execution...'
      break
      
    case 'task':
      currentTask.value = data.task_name
      taskCount.value = data.task_number

      // Track unique tasks only
      if (data.task_name && !seenTasks.value.has(data.task_name)) {
        seenTasks.value.add(data.task_name)
        taskSummary.value.total++
      }
      break

    case 'ok':
      // Count ok tasks separately (not changed)
      if (data.task && !seenTasks.value.has(data.task + '_ok')) {
        seenTasks.value.add(data.task + '_ok')
        taskSummary.value.ok++
      }
      break

    case 'changed':
      // Count changed tasks separately
      if (data.task && !seenTasks.value.has(data.task + '_changed')) {
        seenTasks.value.add(data.task + '_changed')
        taskSummary.value.changed++
      }
      break

    case 'skipped':
      // Count skipped tasks
      if (data.task && !seenTasks.value.has(data.task + '_skipped')) {
        seenTasks.value.add(data.task + '_skipped')
        taskSummary.value.skipped++
      }
      break

    case 'failed':
      // Mark task as failed
      if (data.task && !seenTasks.value.has(data.task + '_failed')) {
        seenTasks.value.add(data.task + '_failed')
        taskSummary.value.failed++
      }
      break
      
    case 'complete':
      duration.value = (Date.now() - startTime.value) / 1000
      status.value = data.status
      message.value = data.message
      completeExecution({
        status: data.status,
        message: data.message,
        duration: duration.value
      })
      break
      
    case 'error':
      status.value = 'error'
      message.value = data.message
      break
  }
}

const completeExecution = (result: any) => {
  isExecuting.value = false
  showResult.value = true
  websocket.value?.close()
  websocket.value = null

  // Emit completion event
  emit('complete', result)

  // Call onComplete prop if provided
  if (props.onComplete) {
    props.onComplete(result)
  }

  // Auto-continue on success after a short delay (unless in test mode)
  if (result.status === 'success' && !props.testMode) {
    setTimeout(() => {
      // Only auto-continue if the modal is still showing (user hasn't manually closed it)
      if (showResult.value && status.value === 'success') {
        closeResult()
      }
    }, 3000) // 3 second delay to show success message
  }
}

const cancelExecution = () => {
  isCancelling.value = true
  websocket.value?.close()
  status.value = 'cancelled'
  message.value = 'Execution was cancelled'
  isExecuting.value = false
  showResult.value = true
  isCancelling.value = false
  
  // Emit completion event with cancelled status
  const result = {
    status: 'cancelled',
    message: 'Execution was cancelled by user',
    duration: duration.value
  }
  emit('complete', result)
  
  // Call onComplete prop if provided
  if (props.onComplete) {
    props.onComplete(result)
  }
}

const closeResult = () => {
  showResult.value = false
  
  // Only emit continue if the playbook was successful
  if (status.value === 'success') {
    emit('continue')
  }
  
  // Reset state
  status.value = 'pending'
  message.value = ''
  currentTask.value = ''
  taskCount.value = 0
  duration.value = null
  logOutput.value = []
  taskSummary.value = { total: 0, ok: 0, changed: 0, skipped: 0, failed: 0 }
  seenTasks.value = new Set()
}

const retry = () => {
  if (props.onRetry) {
    // Close the result modal without emitting continue
    showResult.value = false
    
    // Reset state
    status.value = 'pending'
    message.value = ''
    currentTask.value = ''
    taskCount.value = 0
    duration.value = null
    logOutput.value = []
    taskSummary.value = { total: 0, ok: 0, changed: 0, skipped: 0, failed: 0 }
    seenTasks.value = new Set()

    // Call the retry handler
    props.onRetry()
  }
}

const emitTestPlaybook = () => {
  showResult.value = false
  emit('test-playbook')
}

const emitRollback = () => {
  showResult.value = false
  emit('rollback')
}

const copyOutput = async () => {
  try {
    // Build the output text with metadata
    const header = `Thinkube Installer - Playbook Execution Log
=====================================
Playbook: ${props.playbookName}
Title: ${props.title}
Status: ${status.value}
Duration: ${duration.value ? formatDuration(duration.value) : 'N/A'}
Tasks: Total ${taskSummary.value.total}, OK ${taskSummary.value.ok}, Changed ${taskSummary.value.changed}, Failed ${taskSummary.value.failed}
Timestamp: ${new Date().toISOString()}
=====================================

`
    
    // Combine all log messages
    const logText = logOutput.value
      .map(log => log.message)
      .join('\n')
    
    const fullText = header + logText
    
    // Copy to clipboard
    await navigator.clipboard.writeText(fullText)
    
    // Show success feedback
    copySuccess.value = true
    setTimeout(() => {
      copySuccess.value = false
    }, 2000)
  } catch (err) {
    console.error('Failed to copy output:', err)
    alert('Failed to copy output to clipboard')
  }
}

const formatDuration = (seconds: number): string => {
  if (seconds < 60) {
    return `${seconds.toFixed(1)} seconds`
  } else {
    const minutes = Math.floor(seconds / 60)
    const remainingSeconds = Math.floor(seconds % 60)
    return `${minutes}m ${remainingSeconds}s`
  }
}

const getLogClass = (type: string): string => {
  switch (type) {
    case 'task':
      return 'text-info font-semibold'
    case 'play':
      return 'text-primary font-semibold'
    case 'ok':
      return 'text-success'
    case 'changed':
      return 'text-warning'
    case 'skipped':
      return 'text-info text-opacity-60'
    case 'failed':
      return 'text-error'
    case 'error':
      return 'text-error font-semibold'
    case 'start':
    case 'complete':
      return 'text-accent font-semibold'
    default:
      return 'text-base-content'
  }
}

const getLogPrefix = (type: string): string => {
  switch (type) {
    case 'task':
      return '>'
    case 'play':
      return '#'
    case 'ok':
      return '✓'
    case 'changed':
      return '~'
    case 'skipped':
      return '○'
    case 'failed':
      return '✗'
    case 'error':
      return '!'
    case 'start':
      return '$'
    case 'complete':
      return '>'
    default:
      return ' '
  }
}

// Expose methods to parent component
defineExpose({
  startExecution,
  completeExecution,
  cancelExecution
})
</script>

<style scoped>
/* Compact steps visualization */
.steps-compact {
  gap: 0.25rem;
}

.step-xs::before {
  width: 1rem;
  height: 1rem;
  font-size: 0.6rem;
  line-height: 1rem;
}

.step-xs::after {
  min-width: 0.5rem;
}

/* Hover effect for playbook steps to indicate tooltips */
.step.cursor-help:hover {
  transform: scale(1.15);
  transition: transform 0.2s ease-in-out;
}

.step.cursor-help:hover::before {
  box-shadow: 0 0 8px rgba(59, 130, 246, 0.5);
}

/* Custom scrollbar for log container */
.overflow-y-auto::-webkit-scrollbar {
  width: 8px;
}

.overflow-y-auto::-webkit-scrollbar-track {
  background: rgba(0, 0, 0, 0.2);
  border-radius: 4px;
}

.overflow-y-auto::-webkit-scrollbar-thumb {
  background: rgba(255, 255, 255, 0.3);
  border-radius: 4px;
}

.overflow-y-auto::-webkit-scrollbar-thumb:hover {
  background: rgba(255, 255, 255, 0.5);
}

/* Terminal-like appearance */
.bg-gray-900 {
  background-color: #1a1a1a;
}

/* Override mockup-code background for better contrast */
.mockup-code {
  background-color: #1a1a1a !important;
  color: #e0e0e0 !important;
}

.mockup-code pre {
  color: inherit !important;
}

.mockup-code code {
  color: inherit !important;
  background: transparent !important;
}

/* Ensure prefix symbols are visible */
.mockup-code pre::before {
  color: #666 !important;
}

/* Adjust semantic colors for dark background */
.mockup-code .text-info {
  color: #60a5fa !important; /* Bright blue */
}

.mockup-code .text-success {
  color: #4ade80 !important; /* Bright green */
}

.mockup-code .text-warning {
  color: #fbbf24 !important; /* Bright yellow */
}

.mockup-code .text-error {
  color: #f87171 !important; /* Bright red */
}

.mockup-code .text-primary {
  color: #38bdf8 !important; /* Bright cyan */
}

.mockup-code .text-accent {
  color: #fb923c !important; /* Bright orange */
}

.mockup-code .text-secondary {
  color: #a1a1aa !important; /* Light gray */
}

.mockup-code .text-base-content {
  color: #e0e0e0 !important; /* Light gray for regular text */
}
</style>
