// frontend/src/views/GpuDriverCheck.vue
/*
 * Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
 * SPDX-License-Identifier: Apache-2.0
 */

<template>
  <div class="max-w-6xl mx-auto">
    <h1 class="text-3xl font-bold mb-6 text-base-content">GPU Driver Detection</h1>

    <!-- Loading state -->
    <div v-if="loading" class="flex flex-col items-center justify-center py-12">
      <span class="loading loading-spinner loading-lg"></span>
      <p class="mt-4 text-base-content">Detecting GPUs and drivers on all nodes...</p>
    </div>

    <!-- Error state -->
    <div v-else-if="error" class="alert alert-error mb-6">
      <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
      <span>{{ error }}</span>
    </div>

    <!-- Results -->
    <div v-else-if="nodes.length > 0">
      <!-- Summary card -->
      <div class="card bg-base-100 shadow-xl mb-6">
        <div class="card-body">
          <h2 class="card-title">Detection Summary</h2>
          <div class="grid grid-cols-2 md:grid-cols-4 gap-4 mt-4">
            <div class="stat bg-base-200 rounded-lg">
              <div class="stat-title">Ready</div>
              <div class="stat-value text-success">{{ summary.ready }}</div>
              <div class="stat-desc">Compatible drivers</div>
            </div>
            <div class="stat bg-base-200 rounded-lg">
              <div class="stat-title">Need Install</div>
              <div class="stat-value text-warning">{{ summary.needs_install }}</div>
              <div class="stat-desc">No drivers found</div>
            </div>
            <div class="stat bg-base-200 rounded-lg">
              <div class="stat-title">Need Upgrade</div>
              <div class="stat-value text-error">{{ summary.needs_upgrade }}</div>
              <div class="stat-desc">Old drivers</div>
            </div>
            <div class="stat bg-base-200 rounded-lg">
              <div class="stat-title">No GPU</div>
              <div class="stat-value text-base-content">{{ summary.no_gpu }}</div>
              <div class="stat-desc">CPU only</div>
            </div>
          </div>
        </div>
      </div>

      <!-- Nodes table -->
      <div class="card bg-base-100 shadow-xl mb-6">
        <div class="card-body">
          <h2 class="card-title mb-4">Node Details</h2>
          <div class="overflow-x-auto">
            <table class="table table-zebra">
              <thead>
                <tr>
                  <th>Node</th>
                  <th>GPU</th>
                  <th>Driver Version</th>
                  <th>Status</th>
                  <th>Action Required</th>
                  <th>Your Decision</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="node in nodes" :key="node.ip">
                  <td>
                    <div class="font-bold">{{ node.hostname }}</div>
                    <div class="text-sm opacity-50">{{ node.ip }}</div>
                  </td>
                  <td>
                    <div v-if="node.gpu_detected" class="flex items-center gap-2">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-success" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                      <div>
                        <div class="font-medium">{{ node.gpu_name }}</div>
                        <div class="text-xs opacity-50" v-if="node.gpu_count > 1">{{ node.gpu_count }} GPUs</div>
                      </div>
                    </div>
                    <div v-else class="text-base-content opacity-50">No GPU</div>
                  </td>
                  <td>
                    <span v-if="node.driver_version" class="badge badge-outline">{{ node.driver_version }}</span>
                    <span v-else class="text-base-content opacity-50">Not installed</span>
                  </td>
                  <td>
                    <span v-if="node.driver_status === 'compatible'" class="badge badge-success gap-2">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                      </svg>
                      Compatible
                    </span>
                    <span v-else-if="node.driver_status === 'old'" class="badge badge-error gap-2">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                      </svg>
                      Old ({{ node.min_required_version }}+ required)
                    </span>
                    <span v-else-if="node.driver_status === 'missing'" class="badge badge-warning gap-2">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                      </svg>
                      Missing
                    </span>
                    <span v-else class="badge badge-ghost">{{ node.driver_status }}</span>
                  </td>
                  <td>
                    <span v-if="node.action_required === 'install'" class="text-warning">Install driver</span>
                    <span v-else-if="node.action_required === 'upgrade'" class="text-error">Upgrade driver</span>
                    <span v-else class="text-success">None</span>
                  </td>
                  <td>
                    <!-- Compatible drivers - no decision needed -->
                    <span v-if="node.driver_status === 'compatible'" class="text-success">✓ Ready for GPU</span>

                    <!-- No GPU detected - no decision needed -->
                    <span v-else-if="!node.gpu_detected" class="text-base-content opacity-50">CPU-only node</span>

                    <!-- Missing drivers - offer to install -->
                    <select
                      v-else-if="node.action_required === 'install'"
                      v-model="decisions[node.ip]"
                      class="select select-bordered select-sm"
                    >
                      <option value="">-- Choose action --</option>
                      <option value="install">Install drivers automatically</option>
                      <option value="exclude">Exclude from GPU (CPU-only)</option>
                    </select>

                    <!-- Old drivers - user must upgrade manually -->
                    <select
                      v-else-if="node.action_required === 'upgrade'"
                      v-model="decisions[node.ip]"
                      class="select select-bordered select-sm select-error"
                    >
                      <option value="">-- Choose action --</option>
                      <option value="abort">I will upgrade manually (abort)</option>
                      <option value="exclude">Exclude from GPU (CPU-only)</option>
                    </select>

                    <span v-else class="text-base-content opacity-50">N/A</span>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <!-- Warning for nodes needing manual upgrade -->
      <div v-if="summary.needs_upgrade > 0" class="alert alert-warning mb-6">
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
        </svg>
        <div>
          <h3 class="font-bold">Old NVIDIA Drivers Detected</h3>
          <div class="text-sm mt-1">
            Some nodes have NVIDIA drivers older than version 580.x. GPU Operator v25.3.4 requires driver 580.0 or newer.
            <br><br>
            <strong>To upgrade manually:</strong>
            <ol class="list-decimal list-inside mt-2 ml-4">
              <li>Download driver from: <a href="https://www.nvidia.com/download/index.aspx" target="_blank" class="link">nvidia.com/download</a></li>
              <li>SSH to the node and run: <code class="bg-base-300 px-2 py-1 rounded">sudo sh NVIDIA-Linux-x86_64-580.95.05.run --silent --dkms</code></li>
              <li>Verify with: <code class="bg-base-300 px-2 py-1 rounded">nvidia-smi</code></li>
              <li>Re-run the installer</li>
            </ol>
          </div>
        </div>
      </div>

      <!-- Final decision summary -->
      <div class="card bg-base-100 shadow-xl mb-6">
        <div class="card-body">
          <h2 class="card-title">Deployment Plan</h2>
          <div class="space-y-2 mt-4">
            <p><strong>{{ gpuEnabledCount }}</strong> node(s) will have GPU capabilities enabled</p>
            <p><strong>{{ cpuOnlyCount }}</strong> node(s) will be CPU-only</p>
            <p v-if="installCount > 0" class="text-warning">
              <strong>{{ installCount }}</strong> node(s) will have drivers installed automatically
            </p>
            <p v-if="abortCount > 0" class="text-error">
              <strong>Deployment will abort</strong> - you have chosen to upgrade drivers manually
            </p>
          </div>
        </div>
      </div>

      <!-- Navigation buttons -->
      <div class="flex justify-between mt-8">
        <button type="button" class="btn btn-outline" @click="goBack">
          Back
        </button>
        <button
          type="button"
          class="btn btn-primary"
          @click="continueToDeployment"
          :disabled="!canContinue"
        >
          {{ abortCount > 0 ? 'Abort Deployment' : 'Continue to Deployment' }}
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import axios from 'axios'

const router = useRouter()

const loading = ref(true)
const error = ref('')
const nodes = ref([])
const summary = ref({
  ready: 0,
  needs_install: 0,
  needs_upgrade: 0,
  no_gpu: 0,
  error: 0
})

// User decisions for each node (keyed by IP)
const decisions = ref({})

onMounted(async () => {
  await detectGpuDrivers()
})

async function detectGpuDrivers() {
  try {
    loading.value = true
    error.value = ''

    // Load saved configuration
    const savedConfig = localStorage.getItem('thinkube-config')
    if (!savedConfig) {
      error.value = 'No configuration found. Please complete the Configuration screen first.'
      loading.value = false
      return
    }

    const config = JSON.parse(savedConfig)

    // Load discovered servers from sessionStorage (where they're actually stored)
    const discoveredServers = JSON.parse(sessionStorage.getItem('discoveredServers') || '[]')
    if (discoveredServers.length === 0) {
      error.value = 'No servers discovered. Please complete Server Discovery first.'
      loading.value = false
      return
    }

    // Prepare node list for detection
    const nodeList = discoveredServers.map(server => ({
      hostname: server.hostname || 'unknown',
      ip: server.ip,
      username: server.username,
      password: server.password,
      ssh_key: server.ssh_key
    }))

    // Call detection API
    console.log('Calling GPU detection API with', nodeList.length, 'nodes')
    const response = await axios.post('/api/gpu/detect-drivers', {
      nodes: nodeList
    })

    console.log('GPU detection response:', response.data)

    // Ensure response has expected structure
    if (!response.data || !response.data.nodes) {
      throw new Error('Invalid response from GPU detection API')
    }

    nodes.value = response.data.nodes || []
    summary.value = response.data.summary || {
      ready: 0,
      needs_install: 0,
      needs_upgrade: 0,
      no_gpu: 0,
      error: 0
    }

    // Initialize decisions for nodes that need them
    if (Array.isArray(nodes.value)) {
      nodes.value.forEach(node => {
        if (node.action_required === 'install' || node.action_required === 'upgrade') {
          decisions.value[node.ip] = ''
        }
      })
    }

    loading.value = false
  } catch (e) {
    console.error('Error detecting GPU drivers:', e)
    error.value = e.response?.data?.detail || e.message || 'Failed to detect GPU drivers'
    loading.value = false
    // Ensure nodes is always an array even on error
    nodes.value = []
    summary.value = {
      ready: 0,
      needs_install: 0,
      needs_upgrade: 0,
      no_gpu: 0,
      error: 0
    }
  }
}

// Computed: count nodes that need decisions
const nodesNeedingDecisions = computed(() => {
  if (!nodes.value || !Array.isArray(nodes.value)) return []
  return nodes.value.filter(node =>
    node.action_required === 'install' || node.action_required === 'upgrade'
  )
})

// Computed: check if all decisions are made
const allDecisionsMade = computed(() => {
  const neededDecisions = nodesNeedingDecisions.value
  if (!neededDecisions || neededDecisions.length === 0) return true
  return neededDecisions.every(node => decisions.value && decisions.value[node.ip])
})

// Computed: count nodes with each decision type
const installCount = computed(() => {
  if (!decisions.value) return 0
  return Object.values(decisions.value).filter(d => d === 'install').length
})

const abortCount = computed(() => {
  if (!decisions.value) return 0
  return Object.values(decisions.value).filter(d => d === 'abort').length
})

const excludeCount = computed(() => {
  if (!decisions.value) return 0
  return Object.values(decisions.value).filter(d => d === 'exclude').length
})

const gpuEnabledCount = computed(() => {
  // Nodes with compatible drivers + nodes where we'll install drivers
  return summary.value.ready + installCount.value
})

const cpuOnlyCount = computed(() => {
  // Nodes with no GPU + nodes excluded by user
  return summary.value.no_gpu + excludeCount.value
})

const canContinue = computed(() => {
  // Can continue if all decisions are made
  return allDecisionsMade.value
})

function goBack() {
  router.push('/configuration')
}

async function continueToDeployment() {
  if (!canContinue.value) {
    return
  }

  // If user chose to abort, show confirmation
  if (abortCount.value > 0) {
    const confirmed = confirm(
      'You have chosen to upgrade drivers manually. The deployment will not proceed.\n\n' +
      'After upgrading drivers on the affected nodes, please restart the installer.'
    )
    if (confirmed) {
      // Clear state and go back to welcome
      localStorage.removeItem('thinkube-config')
      localStorage.removeItem('discoveredServers')
      localStorage.removeItem('thinkube-deployment-state-v2')
      router.push('/')
    }
    return
  }

  try {
    // Build GPU node configuration based on decisions
    const gpuNodeConfig = nodes.value.map(node => {
      let gpu_enabled = true
      let driver_preinstalled = false
      let reason = null

      if (!node.gpu_detected) {
        gpu_enabled = false
        reason = 'No GPU detected'
      } else if (node.driver_status === 'compatible') {
        gpu_enabled = true
        driver_preinstalled = true
      } else if (decisions.value[node.ip] === 'install') {
        gpu_enabled = true
        driver_preinstalled = false // Will be installed by playbook
      } else if (decisions.value[node.ip] === 'exclude') {
        gpu_enabled = false
        reason = 'Excluded by user'
      }

      return {
        hostname: node.hostname,
        ip: node.ip,
        gpu_detected: node.gpu_detected,
        gpu_name: node.gpu_name,
        gpu_enabled,
        driver_preinstalled,
        driver_version: node.driver_version,
        needs_driver_install: decisions.value[node.ip] === 'install',
        reason
      }
    })

    // Save GPU configuration to localStorage
    const config = JSON.parse(localStorage.getItem('thinkube-config') || '{}')
    config.gpuNodes = gpuNodeConfig
    localStorage.setItem('thinkube-config', JSON.stringify(config))

    // Save GPU configuration to backend as well
    await axios.post('/api/save-configuration', {
      ...config,
      gpuNodes: gpuNodeConfig
    })

    // Continue to deployment
    router.push('/deploy')
  } catch (e) {
    console.error('Error saving GPU configuration:', e)
    error.value = e.response?.data?.detail || e.message || 'Failed to save GPU configuration'
  }
}
</script>

// frontend/src/pages/gpu-driver-check.tsx
/*
 * Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
 * SPDX-License-Identifier: Apache-2.0
 */

import { useState, useEffect, useMemo } from "react"
import { useNavigate } from "react-router-dom"
import { TkCard, TkCardContent, TkCardHeader, TkCardTitle } from "thinkube-style/components/cards-data"
import { TkAlert, TkAlertDescription } from "thinkube-style/components/feedback"
import { TkButton } from "thinkube-style/components/buttons-badges"
import { TkBadge } from "thinkube-style/components/buttons-badges"
import { TkPageWrapper } from "thinkube-style/components/utilities"
import {
  TkSelect,
  TkSelectContent,
  TkSelectItem,
  TkSelectTrigger,
  TkSelectValue
} from "thinkube-style/components/forms-inputs"
import { CheckCircle2, XCircle, Loader2, AlertCircle } from "lucide-react"
import axios from "@/utils/axios"

interface Node {
  hostname: string
  ip: string
  gpu_detected: boolean
  gpu_name?: string
  gpu_count?: number
  driver_version?: string
  driver_status?: "compatible" | "old" | "missing"
  min_required_version?: string
  action_required?: "install" | "upgrade" | "none"
}

interface Summary {
  ready: number
  needs_install: number
  needs_upgrade: number
  no_gpu: number
  error?: number
}

export default function GpuDriverCheck() {
  const navigate = useNavigate()
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState("")
  const [nodes, setNodes] = useState<Node[]>([])
  const [summary, setSummary] = useState<Summary>({
    ready: 0,
    needs_install: 0,
    needs_upgrade: 0,
    no_gpu: 0,
    error: 0
  })
  const [decisions, setDecisions] = useState<Record<string, string>>({})

  useEffect(() => {
    detectGpuDrivers()
  }, [])

  const detectGpuDrivers = async () => {
    try {
      setLoading(true)
      setError("")

      // Load saved configuration
      const savedConfig = localStorage.getItem("thinkube-config")
      if (!savedConfig) {
        setError("No configuration found. Please complete the Configuration screen first.")
        setLoading(false)
        return
      }

      const config = JSON.parse(savedConfig)

      // Load discovered servers from sessionStorage
      const discoveredServers = JSON.parse(
        sessionStorage.getItem("discoveredServers") || "[]"
      )
      if (discoveredServers.length === 0) {
        setError("No servers discovered. Please complete Server Discovery first.")
        setLoading(false)
        return
      }

      // Prepare node list for detection
      const nodeList = discoveredServers.map((server: any) => ({
        hostname: server.hostname || "unknown",
        ip: server.ip,
        username: server.username,
        password: server.password,
        ssh_key: server.ssh_key
      }))

      // Call detection API
      const response = await axios.post("/api/gpu/detect-drivers", {
        nodes: nodeList
      })

      // Ensure response has expected structure
      if (!response.data || !response.data.nodes) {
        throw new Error("Invalid response from GPU detection API")
      }

      setNodes(response.data.nodes || [])
      setSummary(
        response.data.summary || {
          ready: 0,
          needs_install: 0,
          needs_upgrade: 0,
          no_gpu: 0,
          error: 0
        }
      )

      // Initialize decisions for nodes that need them
      if (Array.isArray(response.data.nodes)) {
        const initialDecisions: Record<string, string> = {}
        response.data.nodes.forEach((node: Node) => {
          if (node.action_required === "install" || node.action_required === "upgrade") {
            initialDecisions[node.ip] = ""
          }
        })
        setDecisions(initialDecisions)
      }

      setLoading(false)
    } catch (e: any) {
      setError(
        e.response?.data?.detail || e.message || "Failed to detect GPU drivers"
      )
      setLoading(false)
      setNodes([])
      setSummary({
        ready: 0,
        needs_install: 0,
        needs_upgrade: 0,
        no_gpu: 0,
        error: 0
      })
    }
  }

  const nodesNeedingDecisions = useMemo(() => {
    if (!nodes || !Array.isArray(nodes)) return []
    return nodes.filter(
      (node) =>
        node.action_required === "install" || node.action_required === "upgrade"
    )
  }, [nodes])

  const allDecisionsMade = useMemo(() => {
    const neededDecisions = nodesNeedingDecisions
    if (!neededDecisions || neededDecisions.length === 0) return true
    return neededDecisions.every((node) => decisions && decisions[node.ip])
  }, [nodesNeedingDecisions, decisions])

  const installCount = useMemo(() => {
    if (!decisions) return 0
    return Object.values(decisions).filter((d) => d === "install").length
  }, [decisions])

  const abortCount = useMemo(() => {
    if (!decisions) return 0
    return Object.values(decisions).filter((d) => d === "abort").length
  }, [decisions])

  const excludeCount = useMemo(() => {
    if (!decisions) return 0
    return Object.values(decisions).filter((d) => d === "exclude").length
  }, [decisions])

  const gpuEnabledCount = useMemo(() => {
    return summary.ready + installCount
  }, [summary.ready, installCount])

  const cpuOnlyCount = useMemo(() => {
    return summary.no_gpu + excludeCount
  }, [summary.no_gpu, excludeCount])

  const canContinue = useMemo(() => {
    return allDecisionsMade
  }, [allDecisionsMade])

  const goBack = () => {
    navigate("/configuration")
  }

  const continueToDeployment = async () => {
    if (!canContinue) {
      return
    }

    // If user chose to abort, show confirmation
    if (abortCount > 0) {
      const confirmed = confirm(
        "You have chosen to upgrade drivers manually. The deployment will not proceed.\n\n" +
          "After upgrading drivers on the affected nodes, please restart the installer."
      )
      if (confirmed) {
        // Clear state and go back to welcome
        localStorage.removeItem("thinkube-config")
        localStorage.removeItem("discoveredServers")
        navigate("/")
      }
      return
    }

    try {
      // Build GPU node configuration based on decisions
      const gpuNodeConfig = nodes.map((node) => {
        let gpu_enabled = true
        let driver_preinstalled = false
        let reason = null

        if (!node.gpu_detected) {
          gpu_enabled = false
          reason = "No GPU detected"
        } else if (node.driver_status === "compatible") {
          gpu_enabled = true
          driver_preinstalled = true
        } else if (decisions[node.ip] === "install") {
          gpu_enabled = true
          driver_preinstalled = false // Will be installed by playbook
        } else if (decisions[node.ip] === "exclude") {
          gpu_enabled = false
          reason = "Excluded by user"
        }

        return {
          hostname: node.hostname,
          ip: node.ip,
          gpu_detected: node.gpu_detected,
          gpu_name: node.gpu_name,
          gpu_enabled,
          driver_preinstalled,
          driver_version: node.driver_version,
          needs_driver_install: decisions[node.ip] === "install",
          reason
        }
      })

      // Save GPU configuration to localStorage
      const config = JSON.parse(localStorage.getItem("thinkube-config") || "{}")
      config.gpuNodes = gpuNodeConfig
      localStorage.setItem("thinkube-config", JSON.stringify(config))

      // Save GPU configuration to backend as well
      await axios.post("/api/save-configuration", {
        ...config,
        gpuNodes: gpuNodeConfig
      })

      // Continue to deployment
      navigate("/deploy")
    } catch (e: any) {
      setError(
        e.response?.data?.detail || e.message || "Failed to save GPU configuration"
      )
    }
  }

  if (loading) {
    return (
      <TkPageWrapper title="GPU Driver Detection">
        <div className="flex flex-col items-center justify-center py-12">
          <Loader2 className="h-12 w-12 animate-spin text-primary mb-4" />
          <p className="text-lg">Detecting GPUs and drivers on all nodes...</p>
        </div>
      </TkPageWrapper>
    )
  }

  if (error) {
    return (
      <TkPageWrapper title="GPU Driver Detection">
        <TkAlert className="bg-destructive/10 text-destructive border-destructive/20 mb-6">
          <XCircle className="h-4 w-4" />
          <TkAlertDescription>{error}</TkAlertDescription>
        </TkAlert>
      </TkPageWrapper>
    )
  }

  return (
    <TkPageWrapper title="GPU Driver Detection">

      {/* Summary card */}
      <TkCard className="mb-6">
        <TkCardHeader>
          <TkCardTitle>Detection Summary</TkCardTitle>
        </TkCardHeader>
        <TkCardContent>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-4">
            <div className="bg-secondary rounded-lg p-4">
              <div className="text-sm text-muted-foreground">Ready</div>
              <div className="text-3xl font-bold text-success">{summary.ready}</div>
              <div className="text-xs text-muted-foreground">Compatible drivers</div>
            </div>
            <div className="bg-secondary rounded-lg p-4">
              <div className="text-sm text-muted-foreground">Need Install</div>
              <div className="text-3xl font-bold text-warning">
                {summary.needs_install}
              </div>
              <div className="text-xs text-muted-foreground">No drivers found</div>
            </div>
            <div className="bg-secondary rounded-lg p-4">
              <div className="text-sm text-muted-foreground">Need Upgrade</div>
              <div className="text-3xl font-bold text-destructive">
                {summary.needs_upgrade}
              </div>
              <div className="text-xs text-muted-foreground">Old drivers</div>
            </div>
            <div className="bg-secondary rounded-lg p-4">
              <div className="text-sm text-muted-foreground">No GPU</div>
              <div className="text-3xl font-bold">{summary.no_gpu}</div>
              <div className="text-xs text-muted-foreground">CPU only</div>
            </div>
          </div>
        </TkCardContent>
      </TkCard>

      {/* Nodes table */}
      <TkCard className="mb-6">
        <TkCardHeader>
          <TkCardTitle className="mb-4">Node Details</TkCardTitle>
        </TkCardHeader>
        <TkCardContent>
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="border-b">
                <tr>
                  <th className="text-left py-2 px-4">Node</th>
                  <th className="text-left py-2 px-4">GPU</th>
                  <th className="text-left py-2 px-4">Driver Version</th>
                  <th className="text-left py-2 px-4">Status</th>
                  <th className="text-left py-2 px-4">Action Required</th>
                  <th className="text-left py-2 px-4">Your Decision</th>
                </tr>
              </thead>
              <tbody>
                {nodes.map((node) => (
                  <tr key={node.ip} className="border-b">
                    <td className="py-2 px-4">
                      <div className="font-bold">{node.hostname}</div>
                      <div className="text-sm text-muted-foreground">{node.ip}</div>
                    </td>
                    <td className="py-2 px-4">
                      {node.gpu_detected ? (
                        <div className="flex items-center gap-2">
                          <CheckCircle2 className="h-5 w-5 text-success" />
                          <div>
                            <div className="font-medium">{node.gpu_name}</div>
                            {node.gpu_count && node.gpu_count > 1 && (
                              <div className="text-xs text-muted-foreground">
                                {node.gpu_count} GPUs
                              </div>
                            )}
                          </div>
                        </div>
                      ) : (
                        <div className="text-muted-foreground">No GPU</div>
                      )}
                    </td>
                    <td className="py-2 px-4">
                      {node.driver_version ? (
                        <TkBadge variant="outline">{node.driver_version}</TkBadge>
                      ) : (
                        <span className="text-muted-foreground">Not installed</span>
                      )}
                    </td>
                    <td className="py-2 px-4">
                      {node.driver_status === "compatible" && (
                        <TkBadge variant="success" className="gap-2">
                          <CheckCircle2 className="h-4 w-4" />
                          Compatible
                        </TkBadge>
                      )}
                      {node.driver_status === "old" && (
                        <TkBadge variant="destructive" className="gap-2">
                          <XCircle className="h-4 w-4" />
                          Old ({node.min_required_version}+ required)
                        </TkBadge>
                      )}
                      {node.driver_status === "missing" && (
                        <TkBadge variant="warning" className="gap-2">
                          <AlertCircle className="h-4 w-4" />
                          Missing
                        </TkBadge>
                      )}
                      {!node.driver_status && (
                        <TkBadge variant="secondary">{node.driver_status}</TkBadge>
                      )}
                    </td>
                    <td className="py-2 px-4">
                      {node.action_required === "install" && (
                        <span className="text-warning">Install driver</span>
                      )}
                      {node.action_required === "upgrade" && (
                        <span className="text-destructive">Upgrade driver</span>
                      )}
                      {node.action_required === "none" && (
                        <span className="text-success">None</span>
                      )}
                      {!node.action_required && <span>-</span>}
                    </td>
                    <td className="py-2 px-4">
                      {node.driver_status === "compatible" && (
                        <span className="text-success">Ready for GPU</span>
                      )}
                      {!node.gpu_detected && (
                        <span className="text-muted-foreground">CPU-only node</span>
                      )}
                      {node.action_required === "install" && (
                        <TkSelect
                          value={decisions[node.ip] || ""}
                          onValueChange={(value: string) =>
                            setDecisions({ ...decisions, [node.ip]: value })
                          }
                        >
                          <TkSelectTrigger className="w-[200px]">
                            <TkSelectValue placeholder="-- Choose action --" />
                          </TkSelectTrigger>
                          <TkSelectContent>
                            <TkSelectItem value="install">
                              Install drivers automatically
                            </TkSelectItem>
                            <TkSelectItem value="exclude">
                              Exclude from GPU (CPU-only)
                            </TkSelectItem>
                          </TkSelectContent>
                        </TkSelect>
                      )}
                      {node.action_required === "upgrade" && (
                        <TkSelect
                          value={decisions[node.ip] || ""}
                          onValueChange={(value: string) =>
                            setDecisions({ ...decisions, [node.ip]: value })
                          }
                        >
                          <TkSelectTrigger className="w-[200px]">
                            <TkSelectValue placeholder="-- Choose action --" />
                          </TkSelectTrigger>
                          <TkSelectContent>
                            <TkSelectItem value="abort">
                              I will upgrade manually (abort)
                            </TkSelectItem>
                            <TkSelectItem value="exclude">
                              Exclude from GPU (CPU-only)
                            </TkSelectItem>
                          </TkSelectContent>
                        </TkSelect>
                      )}
                      {!node.action_required &&
                        node.driver_status !== "compatible" &&
                        node.gpu_detected && <span className="text-muted-foreground">N/A</span>}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </TkCardContent>
      </TkCard>

      {/* Warning for nodes needing manual upgrade */}
      {summary.needs_upgrade > 0 && (
        <TkAlert className="bg-warning/10 text-warning border-warning/20 mb-6">
          <AlertCircle className="h-4 w-4" />
          <TkAlertDescription>
            <div>
              <h3 className="font-bold">Old NVIDIA Drivers Detected</h3>
              <div className="text-sm mt-1">
                Some nodes have NVIDIA drivers older than version 580.x. GPU
                Operator v25.3.4 requires driver 580.0 or newer.
                <br />
                <br />
                <strong>To upgrade manually:</strong>
                <ol className="list-decimal list-inside mt-2 ml-4">
                  <li>
                    Download driver from:{" "}
                    <a
                      href="https://www.nvidia.com/download/index.aspx"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="underline"
                    >
                      nvidia.com/download
                    </a>
                  </li>
                  <li>
                    SSH to the node and run:{" "}
                    <code className="bg-secondary px-2 py-1 rounded">
                      sudo sh NVIDIA-Linux-x86_64-580.95.05.run --silent --dkms
                    </code>
                  </li>
                  <li>
                    Verify with:{" "}
                    <code className="bg-secondary px-2 py-1 rounded">
                      nvidia-smi
                    </code>
                  </li>
                  <li>Re-run the installer</li>
                </ol>
              </div>
            </div>
          </TkAlertDescription>
        </TkAlert>
      )}

      {/* Final decision summary */}
      <TkCard className="mb-6">
        <TkCardHeader>
          <TkCardTitle>Deployment Plan</TkCardTitle>
        </TkCardHeader>
        <TkCardContent className="space-y-2">
          <p>
            <strong>{gpuEnabledCount}</strong> node(s) will have GPU capabilities
            enabled
          </p>
          <p>
            <strong>{cpuOnlyCount}</strong> node(s) will be CPU-only
          </p>
          {installCount > 0 && (
            <p className="text-warning">
              <strong>{installCount}</strong> node(s) will have drivers installed
              automatically
            </p>
          )}
          {abortCount > 0 && (
            <p className="text-destructive">
              <strong>Deployment will abort</strong> - you have chosen to upgrade
              drivers manually
            </p>
          )}
        </TkCardContent>
      </TkCard>

      {/* Navigation buttons */}
      <div className="flex justify-between mt-8">
        <TkButton variant="outline" onClick={goBack}>
          Back
        </TkButton>
        <TkButton onClick={continueToDeployment} disabled={!canContinue}>
          {abortCount > 0 ? "Abort Deployment" : "Continue to Deployment"}
        </TkButton>
      </div>
    </TkPageWrapper>
  )
}
