// frontend/src/views/ServerDiscovery.vue
/*
 * Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
 * SPDX-License-Identifier: Apache-2.0
 */

<template>
  <div class="max-w-6xl mx-auto">
    <h1 class="text-3xl font-bold mb-6">Server Discovery</h1>
    
    <!-- Network Mode Selection -->
    <div class="card bg-base-100 shadow-xl mb-6">
      <div class="card-body">
        <h2 class="card-title mb-4">Network Mode</h2>
        <p class="text-sm text-base-content text-opacity-70 mb-4">
          Choose how to discover your servers. ZeroTier is recommended for distributed nodes.
        </p>
        
        <div class="form-control">
          <div class="flex flex-col gap-2">
            <label class="label cursor-pointer justify-start gap-4">
              <input 
                v-model="networkMode" 
                type="radio" 
                name="networkMode" 
                value="overlay" 
                class="radio radio-primary" 
                @change="onNetworkModeChange"
              />
              <div class="flex flex-col">
                <span class="label-text font-medium">Overlay Network (ZeroTier) - Recommended</span>
                <span class="label-text-alt text-sm">Discover nodes on your ZeroTier network</span>
              </div>
            </label>
            <label class="label cursor-pointer justify-start gap-4">
              <input 
                v-model="networkMode" 
                type="radio" 
                name="networkMode" 
                value="local" 
                class="radio radio-primary" 
                @change="onNetworkModeChange"
              />
              <div class="flex flex-col">
                <span class="label-text font-medium">Local Network</span>
                <span class="label-text-alt text-sm">Scan your local network for Ubuntu servers</span>
              </div>
            </label>
          </div>
        </div>
        
      </div>
    </div>
    
    <!-- Discovery Controls -->
    <div class="card bg-base-100 shadow-xl mb-6">
      <div class="card-body">
        <h2 class="card-title mb-4">{{ networkMode === 'overlay' ? 'Discover ZeroTier Nodes' : 'Scan Network for Ubuntu Servers' }}</h2>
        
        <div class="mb-4">
          <div class="form-control">
            <label class="label">
              <span class="label-text">{{ networkMode === 'overlay' ? 'ZeroTier Network CIDR' : 'Network CIDR' }}</span>
              <span class="label-text-alt">{{ networkMode === 'overlay' ? 'e.g., 172.30.0.0/24' : 'e.g., 192.168.1.0/24' }}</span>
            </label>
            <input 
              v-model="networkCIDR" 
              type="text" 
              :placeholder="networkMode === 'overlay' ? 'Enter your ZeroTier network CIDR' : '192.168.1.0/24'" 
              class="input input-md"
              :disabled="isScanning"
            />
          </div>
        </div>
        
        <div class="flex items-center gap-4">
          <button 
            class="btn btn-primary"
            @click="startDiscovery"
            :disabled="isScanning"
          >
            <span v-if="isScanning" class="loading loading-spinner"></span>
            <svg v-else class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
            </svg>
            {{ isScanning ? 'Discovering...' : networkMode === 'overlay' ? 'Discover ZeroTier Nodes' : 'Start Network Scan' }}
          </button>
        </div>
      </div>
    </div>
    
    <!-- Scanning Progress -->
    <div v-if="isScanning" class="card bg-base-100 shadow-xl mb-6">
      <div class="card-body">
        <div class="flex justify-between items-center mb-4">
          <div>
            <p class="text-lg font-semibold">Scanning Network...</p>
            <p class="text-sm text-base-content text-opacity-70">{{ scanStatus }}</p>
          </div>
          <div class="text-2xl font-bold text-primary">{{ Math.round(scanProgress) }}%</div>
        </div>
        <progress class="progress progress-primary w-full" :value="scanProgress" max="100"></progress>
      </div>
    </div>
    
    <!-- Discovered Servers -->
    <div v-if="discoveredServers.length > 0" class="card bg-base-100 shadow-xl mb-6">
      <div class="card-body">
        <h2 class="card-title mb-4">
          Discovered Servers
          <div class="badge badge-primary">{{ discoveredServers.length }}</div>
        </h2>
        
        <div class="space-y-4">
          <div 
            v-for="server in discoveredServers" 
            :key="server.ip"
            class="card bg-base-200 shadow-sm"
          >
            <div class="card-body p-4">
              <div class="flex items-center justify-between">
                <div class="flex items-center gap-4">
                  <!-- Confidence Icon -->
                  <div class="flex-shrink-0">
                    <div v-if="server.confidence === 'confirmed'" class="tooltip" data-tip="Confirmed Ubuntu">
                      <svg class="w-8 h-8 text-success" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                      </svg>
                    </div>
                    <div v-else-if="server.confidence === 'possible'" class="tooltip" data-tip="Possible Ubuntu">
                      <svg class="w-8 h-8 text-warning" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                      </svg>
                    </div>
                    <div v-else-if="server.confidence === 'failed'" class="tooltip" data-tip="SSH Verification Failed">
                      <svg class="w-8 h-8 text-error" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                      </svg>
                    </div>
                    <div v-else class="tooltip" data-tip="Unknown OS">
                      <svg class="w-8 h-8 text-base-content text-opacity-30" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                      </svg>
                    </div>
                  </div>
                  
                  <!-- Server Info -->
                  <div>
                    <h3 class="font-semibold text-lg">
                      {{ server.ip }}
                      <span v-if="server.hostname" class="text-sm text-base-content text-opacity-70 ml-2">
                        ({{ server.hostname }})
                      </span>
                    </h3>
                    <div class="text-sm text-base-content text-opacity-70">
                      <span v-if="server.error" class="text-error">{{ server.error }}</span>
                      <span v-else-if="server.os_info">{{ server.os_info }}</span>
                      <span v-else-if="server.ssh_available">SSH Available</span>
                      <span v-else>No SSH Access</span>
                      <span v-if="server.banner && !server.error" class="ml-2 font-mono text-xs">
                        • {{ server.banner.substring(0, 30) }}...
                      </span>
                    </div>
                  </div>
                </div>
                
                <!-- Actions -->
                <div class="flex items-center gap-2">
                  <button 
                    v-if="server.confidence === 'possible'"
                    class="btn btn-sm btn-ghost"
                    @click="verifyServer(server)"
                  >
                    Verify
                  </button>
                  <button 
                    v-if="server.ssh_available && !server.error && !selectedServers.find(s => s.ip === server.ip)"
                    class="btn btn-sm btn-primary"
                    @click="selectServer(server)"
                  >
                    Select
                  </button>
                  <button 
                    v-else-if="server.error"
                    class="btn btn-sm btn-error"
                    disabled
                  >
                    Failed
                  </button>
                  <div v-else-if="selectedServers.find(s => s.ip === server.ip)" class="badge badge-success">
                    Selected
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    
    <!-- Navigation -->
    <div class="flex justify-between mt-6">
      <button class="btn btn-ghost gap-2" @click="$router.push('/installation')">
        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
        </svg>
        Back
      </button>
      <button 
        class="btn btn-primary gap-2"
        @click="proceedToNodeConfig"
        :disabled="selectedServers.length === 0"
      >
        Continue with {{ selectedServers.length }} Server{{ selectedServers.length !== 1 ? 's' : '' }}
        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
        </svg>
      </button>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import axios from '@/utils/axios'

const router = useRouter()

// Get network mode from config
const config = ref(JSON.parse(localStorage.getItem('thinkube-config') || '{}'))
const networkMode = ref(config.value.networkMode || 'overlay')

// State
const networkCIDR = ref('192.168.1.0/24')
const testMode = ref(false)
const isScanning = ref(false)
const scanProgress = ref(0)
const scanStatus = ref('')
const discoveredServers = ref([])
const selectedServers = ref([])


// Methods
const onNetworkModeChange = async () => {
  // Save the network mode to config
  config.value.networkMode = networkMode.value
  localStorage.setItem('thinkube-config', JSON.stringify(config.value))
  
  // Clear any discovered servers when switching modes
  discoveredServers.value = []
  selectedServers.value = []
  
  // Update default CIDR based on mode
  if (networkMode.value === 'overlay') {
    // Try to auto-detect ZeroTier network
    try {
      const response = await axios.get('/api/zerotier-network')
      if (response.data.detected) {
        networkCIDR.value = response.data.network_cidr
        console.log(`Auto-detected ZeroTier network: ${response.data.network_cidr}`)
      } else {
        networkCIDR.value = ''  // No default - user must provide
      }
    } catch (error) {
      networkCIDR.value = '172.30.0.0/24'  // Fallback default
    }
  } else {
    // For local mode, try to auto-detect
    autoDetectNetwork()
  }
}

const startDiscovery = async () => {
  isScanning.value = true
  scanProgress.value = 0
  scanStatus.value = networkMode.value === 'overlay' ? 'Connecting to ZeroTier API...' : 'Initializing scan...'
  discoveredServers.value = []
  
  if (networkMode.value === 'overlay') {
    // ZeroTier discovery - scan the ZeroTier network directly
    // Users should enter their ZeroTier network CIDR (e.g., 172.30.0.0/24)
    const progressInterval = setInterval(() => {
      if (scanProgress.value < 90) {
        scanProgress.value = Math.min(90, scanProgress.value + Math.random() * 20)
        scanStatus.value = `Scanning ZeroTier network ${networkCIDR.value} - Checking ${Math.floor(scanProgress.value * 2.54)} of 254 hosts`
      } else {
        // At 90%, show that backend is still processing
        scanStatus.value = 'Processing results...'
      }
    }, 500)
    
    try {
      const sudoPassword = sessionStorage.getItem('sudoPassword')
      const currentUsername = sessionStorage.getItem('systemUsername')

      const response = await axios.post('/api/discover-servers', {
        network_cidr: networkCIDR.value,
        test_mode: testMode.value,
        username: currentUsername,
        password: sudoPassword
      }, {
        timeout: 120000  // 2 minutes for network discovery
      })
      
      discoveredServers.value = response.data.servers || []
      scanProgress.value = 100
      scanStatus.value = `Scan complete - Found ${discoveredServers.value.length} servers on ZeroTier network`
      
    } catch (error) {
      console.error('Discovery failed:', error)
      scanStatus.value = 'Scan failed: ' + error.message
    } finally {
      clearInterval(progressInterval)
      setTimeout(() => {
        isScanning.value = false
      }, 1000)
    }
  } else {
    // Local network discovery
    const progressInterval = setInterval(() => {
      if (scanProgress.value < 90) {
        scanProgress.value = Math.min(90, scanProgress.value + Math.random() * 20)
        scanStatus.value = `Scanning ${networkCIDR.value} - Checking ${Math.floor(scanProgress.value * 2.54)} of 254 hosts`
      } else {
        // At 90%, show that backend is still processing
        scanStatus.value = 'Processing results...'
      }
    }, 500)
    
    try {
      const sudoPassword = sessionStorage.getItem('sudoPassword')
      const currentUsername = sessionStorage.getItem('systemUsername')

      const response = await axios.post('/api/discover-servers', {
        network_cidr: networkCIDR.value,
        test_mode: testMode.value,
        username: currentUsername,
        password: sudoPassword
      }, {
        timeout: 120000  // 2 minutes for network discovery
      })
      
      discoveredServers.value = response.data.servers || []
      scanProgress.value = 100
      scanStatus.value = `Scan complete - Found ${discoveredServers.value.length} servers`
      
    } catch (error) {
      console.error('Discovery failed:', error)
      scanStatus.value = 'Scan failed: ' + error.message
    } finally {
      clearInterval(progressInterval)
      setTimeout(() => {
        isScanning.value = false
      }, 1000)
    }
  }
}

const verifyServer = async (server) => {
  try {
    // Get password from sessionStorage
    const sudoPassword = sessionStorage.getItem('sudoPassword')
    
    const endpoint = server.is_zerotier ? '/api/verify-zerotier-ssh' : '/api/verify-server-ssh'
    const response = await axios.post(endpoint, {
      ip_address: server.ip,
      zerotier_ip: server.ip,  // For ZeroTier endpoint
      password: sudoPassword,
      test_mode: testMode.value
    })
    
    // Update server info based on verification
    const idx = discoveredServers.value.findIndex(s => s.ip === server.ip)
    if (idx >= 0) {
      if (response.data.connected) {
        discoveredServers.value[idx] = {
          ...discoveredServers.value[idx],
          hostname: response.data.hostname || server.hostname,
          os_info: response.data.os_info,
          confidence: response.data.os_info?.includes('24.04') ? 'confirmed' : 'possible',
          verified: true
        }
      } else {
        // SSH verification failed - show the error
        discoveredServers.value[idx] = {
          ...discoveredServers.value[idx],
          error: response.data.message || 'SSH verification failed',
          verified: false,
          confidence: 'failed'
        }
        // Show error to user
        alert(`SSH verification failed for ${server.ip}:\n${response.data.message}`)
      }
    }
  } catch (error) {
    console.error('Verification failed:', error)
    // Show error to user
    alert(`Failed to verify server ${server.ip}:\n${error.response?.data?.detail || error.message}`)
  }
}

const selectServer = (server) => {
  if (!selectedServers.value.find(s => s.ip === server.ip)) {
    selectedServers.value.push(server)
  }
}


const proceedToNodeConfig = () => {
  // Debug log to see what we're storing
  console.log('Selected servers:', selectedServers.value)
  
  // Store selected servers in a shared store or pass via router
  sessionStorage.setItem('selectedServers', JSON.stringify(selectedServers.value))
  sessionStorage.setItem('testMode', testMode.value)
  // Store discovered servers - these should have full server objects with hostnames
  sessionStorage.setItem('discoveredServers', JSON.stringify(selectedServers.value))
  // Store network CIDR for inventory generation
  sessionStorage.setItem('networkCIDR', networkCIDR.value)
  router.push('/ssh-setup')
}

const autoDetectNetwork = async () => {
  try {
    const response = await axios.get('/api/local-network')
    if (response.data.detected) {
      networkCIDR.value = response.data.network_cidr
      console.log(`Auto-detected network: ${response.data.network_cidr}`)
    }
  } catch (error) {
    console.error('Failed to auto-detect network:', error)
    // Keep default value
  }
}

// Auto-detect network on mount
onMounted(async () => {
  // Set initial CIDR based on network mode
  if (networkMode.value === 'overlay') {
    // Try to auto-detect ZeroTier network
    try {
      const response = await axios.get('/api/zerotier-network')
      if (response.data.detected) {
        networkCIDR.value = response.data.network_cidr
        console.log(`Auto-detected ZeroTier network: ${response.data.network_cidr} on ${response.data.interface}`)
      } else {
        // Fallback to common default
        networkCIDR.value = '172.30.0.0/24'
        if (response.data.message) {
          console.log(response.data.message)
        }
      }
    } catch (error) {
      console.error('Failed to auto-detect ZeroTier network:', error)
      networkCIDR.value = ''  // No default - user must provide or auto-detect
    }
  } else {
    await autoDetectNetwork()
  }
})
</script>

// frontend/src/pages/server-discovery.tsx
/*
 * Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
 * SPDX-License-Identifier: Apache-2.0
 */

import { useState, useEffect } from "react"
import { useNavigate } from "react-router-dom"
import { TkCard, TkCardContent, TkCardHeader, TkCardTitle } from "thinkube-style/components/cards-data"
import { TkAlert, TkAlertDescription } from "thinkube-style/components/feedback"
import { TkButton } from "thinkube-style/components/buttons-badges"
import { TkBadge } from "thinkube-style/components/buttons-badges"
import { TkProgress } from "thinkube-style/components/feedback"
import { TkInput } from "thinkube-style/components/forms-inputs"
import { TkLabel } from "thinkube-style/components/forms-inputs"
import { TkRadioGroup, TkRadioGroupItem } from "thinkube-style/components/forms-inputs"
import { TkPageWrapper } from "thinkube-style/components/utilities"
import {
  Search,
  ChevronLeft,
  ChevronRight,
  CheckCircle2,
  AlertCircle,
  XCircle,
  HelpCircle,
  Loader2
} from "lucide-react"
import axios from "@/utils/axios"

interface Server {
  ip: string
  hostname?: string
  os_info?: string
  ssh_available?: boolean
  confidence?: "confirmed" | "possible" | "failed" | "unknown"
  error?: string
  banner?: string
}

interface DiscoveredServer extends Server {
  is_zerotier?: boolean
}

export default function ServerDiscovery() {
  const navigate = useNavigate()

  const [config] = useState(() => {
    if (typeof window !== "undefined") {
      return JSON.parse(localStorage.getItem("thinkube-config") || "{}")
    }
    return {}
  })

  const [networkMode, setNetworkMode] = useState(config.networkMode || "overlay")
  const [networkCIDR, setNetworkCIDR] = useState("192.168.1.0/24")
  const [isScanning, setIsScanning] = useState(false)
  const [scanProgress, setScanProgress] = useState(0)
  const [scanStatus, setScanStatus] = useState("")
  const [discoveredServers, setDiscoveredServers] = useState<DiscoveredServer[]>([])
  const [selectedServers, setSelectedServers] = useState<DiscoveredServer[]>([])

  useEffect(() => {
    const loadInitialData = async () => {
      if (networkMode === "overlay") {
        try {
          const response = await axios.get("/api/zerotier-network")
          if (response.data.detected) {
            setNetworkCIDR(response.data.network_cidr)
          } else {
            setNetworkCIDR("172.30.0.0/24")
          }
        } catch (error) {
          setNetworkCIDR("172.30.0.0/24")
        }
      } else {
        await autoDetectNetwork()
      }
    }

    loadInitialData()
  }, [])

  const autoDetectNetwork = async () => {
    try {
      const response = await axios.get("/api/local-network")
      if (response.data.detected) {
        setNetworkCIDR(response.data.network_cidr)
      }
    } catch (error) {
      // Keep default value
    }
  }

  const onNetworkModeChange = async (value: string) => {
    setNetworkMode(value)

    if (typeof window !== "undefined") {
      const updatedConfig = { ...config, networkMode: value }
      localStorage.setItem("thinkube-config", JSON.stringify(updatedConfig))
    }

    setDiscoveredServers([])
    setSelectedServers([])

    if (value === "overlay") {
      try {
        const response = await axios.get("/api/zerotier-network")
        if (response.data.detected) {
          setNetworkCIDR(response.data.network_cidr)
        } else {
          setNetworkCIDR("")
        }
      } catch (error) {
        setNetworkCIDR("172.30.0.0/24")
      }
    } else {
      await autoDetectNetwork()
    }
  }

  const startDiscovery = async () => {
    setIsScanning(true)
    setScanProgress(0)
    setScanStatus(
      networkMode === "overlay"
        ? "Connecting to ZeroTier API..."
        : "Initializing scan..."
    )
    setDiscoveredServers([])

    const progressInterval = setInterval(() => {
      setScanProgress((prev) => {
        if (prev < 90) {
          const newProgress = Math.min(90, prev + Math.random() * 20)
          setScanStatus(
            networkMode === "overlay"
              ? `Scanning ZeroTier network ${networkCIDR} - Checking ${Math.floor(newProgress * 2.54)} of 254 hosts`
              : `Scanning ${networkCIDR} - Checking ${Math.floor(newProgress * 2.54)} of 254 hosts`
          )
          return newProgress
        } else {
          setScanStatus("Processing results...")
          return prev
        }
      })
    }, 500)

    try {
      const sudoPassword = sessionStorage.getItem("sudoPassword")
      const currentUsername = sessionStorage.getItem("systemUsername")

      const response = await axios.post(
        "/api/discover-servers",
        {
          network_cidr: networkCIDR,
          test_mode: false,
          username: currentUsername,
          password: sudoPassword
        },
        {
          timeout: 120000
        }
      )

      setDiscoveredServers(response.data.servers || [])
      setScanProgress(100)
      setScanStatus(
        networkMode === "overlay"
          ? `Scan complete - Found ${response.data.servers?.length || 0} servers on ZeroTier network`
          : `Scan complete - Found ${response.data.servers?.length || 0} servers`
      )
    } catch (error: any) {
      setScanStatus("Scan failed: " + error.message)
    } finally {
      clearInterval(progressInterval)
      setTimeout(() => {
        setIsScanning(false)
      }, 1000)
    }
  }

  const verifyServer = async (server: DiscoveredServer) => {
    try {
      const sudoPassword = sessionStorage.getItem("sudoPassword")

      const endpoint = server.is_zerotier
        ? "/api/verify-zerotier-ssh"
        : "/api/verify-server-ssh"
      const response = await axios.post(endpoint, {
        ip_address: server.ip,
        zerotier_ip: server.ip,
        password: sudoPassword,
        test_mode: false
      })

      const idx = discoveredServers.findIndex((s) => s.ip === server.ip)
      if (idx >= 0) {
        const updatedServers = [...discoveredServers]
        if (response.data.connected) {
          updatedServers[idx] = {
            ...updatedServers[idx],
            hostname: response.data.hostname || server.hostname,
            os_info: response.data.os_info,
            confidence: response.data.os_info?.includes("24.04")
              ? "confirmed"
              : "possible",
            error: undefined
          }
        } else {
          updatedServers[idx] = {
            ...updatedServers[idx],
            error: response.data.message || "SSH verification failed",
            confidence: "failed"
          }
          alert(
            `SSH verification failed for ${server.ip}:\n${response.data.message}`
          )
        }
        setDiscoveredServers(updatedServers)
      }
    } catch (error: any) {
      alert(
        `Failed to verify server ${server.ip}:\n${error.response?.data?.detail || error.message}`
      )
    }
  }

  const selectServer = (server: DiscoveredServer) => {
    if (!selectedServers.find((s) => s.ip === server.ip)) {
      setSelectedServers([...selectedServers, server])
    }
  }

  const proceedToNodeConfig = () => {
    sessionStorage.setItem("selectedServers", JSON.stringify(selectedServers))
    sessionStorage.setItem("testMode", "false")
    sessionStorage.setItem("discoveredServers", JSON.stringify(selectedServers))
    sessionStorage.setItem("networkCIDR", networkCIDR)
    navigate("/ssh-setup")
  }

  const getConfidenceIcon = (confidence?: string) => {
    switch (confidence) {
      case "confirmed":
        return <CheckCircle2 className="w-8 h-8 text-success" />
      case "possible":
        return <AlertCircle className="w-8 h-8 text-warning" />
      case "failed":
        return <AlertCircle className="w-8 h-8 text-destructive" />
      default:
        return <HelpCircle className="w-8 h-8 text-muted-foreground" />
    }
  }

  const getConfidenceTooltip = (confidence?: string) => {
    switch (confidence) {
      case "confirmed":
        return "Confirmed Ubuntu"
      case "possible":
        return "Possible Ubuntu"
      case "failed":
        return "SSH Verification Failed"
      default:
        return "Unknown OS"
    }
  }

  return (
    <TkPageWrapper title="Server Discovery">
      {/* Network Mode Selection */}
      <TkCard className="mb-6">
        <TkCardHeader>
          <TkCardTitle>Network Mode</TkCardTitle>
        </TkCardHeader>
        <TkCardContent>
          <p className="text-sm text-muted-foreground mb-4">
            Choose how to discover your servers. ZeroTier is recommended for
            distributed nodes.
          </p>

          <TkRadioGroup
            value={networkMode}
            onValueChange={onNetworkModeChange}
            className="gap-4"
          >
            <div className="flex items-start gap-4 cursor-pointer">
              <TkRadioGroupItem value="overlay" id="overlay" />
              <TkLabel htmlFor="overlay" className="cursor-pointer flex-1">
                <div className="flex flex-col gap-1">
                  <span className="font-medium">
                    Overlay Network (ZeroTier) - Recommended
                  </span>
                  <span className="text-sm text-muted-foreground">
                    Discover nodes on your ZeroTier network
                  </span>
                </div>
              </TkLabel>
            </div>
            <div className="flex items-start gap-4 cursor-pointer">
              <TkRadioGroupItem value="local" id="local" />
              <TkLabel htmlFor="local" className="cursor-pointer flex-1">
                <div className="flex flex-col gap-1">
                  <span className="font-medium">Local Network</span>
                  <span className="text-sm text-muted-foreground">
                    Scan your local network for Ubuntu servers
                  </span>
                </div>
              </TkLabel>
            </div>
          </TkRadioGroup>
        </TkCardContent>
      </TkCard>

      {/* Discovery Controls */}
      <TkCard className="mb-6">
        <TkCardHeader>
          <TkCardTitle>
            {networkMode === "overlay"
              ? "Discover ZeroTier Nodes"
              : "Scan Network for Ubuntu Servers"}
          </TkCardTitle>
        </TkCardHeader>
        <TkCardContent>
          <div className="mb-4">
            <div className="flex justify-between items-end mb-2">
              <TkLabel htmlFor="networkCIDR">
                {networkMode === "overlay"
                  ? "ZeroTier Network CIDR"
                  : "Network CIDR"}
              </TkLabel>
              <span className="text-sm text-muted-foreground">
                {networkMode === "overlay"
                  ? "e.g., 172.30.0.0/24"
                  : "e.g., 192.168.1.0/24"}
              </span>
            </div>
            <TkInput
              id="networkCIDR"
              value={networkCIDR}
              onChange={(e: React.ChangeEvent<HTMLInputElement>) => setNetworkCIDR(e.target.value)}
              placeholder={
                networkMode === "overlay"
                  ? "Enter your ZeroTier network CIDR"
                  : "192.168.1.0/24"
              }
              disabled={isScanning}
            />
          </div>

          <div className="flex items-center gap-4">
            <TkButton onClick={startDiscovery} disabled={isScanning}>
              {isScanning ? (
                <Loader2 className="w-5 h-5 animate-spin" />
              ) : (
                <Search className="w-5 h-5" />
              )}
              {isScanning
                ? "Discovering..."
                : networkMode === "overlay"
                  ? "Discover ZeroTier Nodes"
                  : "Start Network Scan"}
            </TkButton>
          </div>
        </TkCardContent>
      </TkCard>

      {/* Scanning TkProgress */}
      {isScanning && (
        <TkCard className="mb-6">
          <TkCardContent className="pt-6">
            <div className="flex justify-between items-center mb-4">
              <div>
                <p className="text-lg font-semibold">Scanning Network...</p>
                <p className="text-sm text-muted-foreground">{scanStatus}</p>
              </div>
              <div className="text-2xl font-bold text-primary">
                {Math.round(scanProgress)}%
              </div>
            </div>
            <TkProgress value={scanProgress} />
          </TkCardContent>
        </TkCard>
      )}

      {/* Discovered Servers */}
      {discoveredServers.length > 0 && (
        <TkCard className="mb-6">
          <TkCardHeader>
            <div className="flex items-center gap-2">
              <TkCardTitle>Discovered Servers</TkCardTitle>
              <TkBadge variant="default">{discoveredServers.length}</TkBadge>
            </div>
          </TkCardHeader>
          <TkCardContent>
            <div className="space-y-4">
              {discoveredServers.map((server) => (
                <TkCard key={server.ip} className="bg-muted/50">
                  <TkCardContent className="p-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-4">
                        <div
                          className="flex-shrink-0"
                          title={getConfidenceTooltip(server.confidence)}
                        >
                          {getConfidenceIcon(server.confidence)}
                        </div>

                        <div>
                          <h3 className="font-semibold text-lg">
                            {server.ip}
                            {server.hostname && (
                              <span className="text-sm text-muted-foreground ml-2">
                                ({server.hostname})
                              </span>
                            )}
                          </h3>
                          <div className="text-sm text-muted-foreground">
                            {server.error ? (
                              <span className="text-destructive">
                                {server.error}
                              </span>
                            ) : server.os_info ? (
                              <span>{server.os_info}</span>
                            ) : server.ssh_available ? (
                              <span>SSH Available</span>
                            ) : (
                              <span>No SSH Access</span>
                            )}
                            {server.banner && !server.error && (
                              <span className="ml-2 font-mono text-xs">
                                • {server.banner.substring(0, 30)}...
                              </span>
                            )}
                          </div>
                        </div>
                      </div>

                      <div className="flex items-center gap-2">
                        {server.confidence === "possible" && (
                          <TkButton
                            size="sm"
                            variant="ghost"
                            onClick={() => verifyServer(server)}
                          >
                            Verify
                          </TkButton>
                        )}
                        {server.ssh_available &&
                          !server.error &&
                          !selectedServers.find((s) => s.ip === server.ip) && (
                            <TkButton
                              size="sm"
                              onClick={() => selectServer(server)}
                            >
                              Select
                            </TkButton>
                          )}
                        {server.error && (
                          <TkButton size="sm" variant="destructive" disabled>
                            Failed
                          </TkButton>
                        )}
                        {selectedServers.find((s) => s.ip === server.ip) && (
                          <TkBadge variant="success">Selected</TkBadge>
                        )}
                      </div>
                    </div>
                  </TkCardContent>
                </TkCard>
              ))}
            </div>
          </TkCardContent>
        </TkCard>
      )}

      {/* Navigation */}
      <div className="flex justify-between mt-6">
        <TkButton
          variant="ghost"
          className="gap-2"
          onClick={() => navigate("/installation")}
        >
          <ChevronLeft className="w-5 h-5" />
          Back
        </TkButton>
        <TkButton
          className="gap-2"
          onClick={proceedToNodeConfig}
          disabled={selectedServers.length === 0}
        >
          Setup SSH Connectivity
          <ChevronRight className="w-5 h-5" />
        </TkButton>
      </div>
    </TkPageWrapper>
  )
}
