// frontend/src/views/Welcome.vue
/*
 * Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
 * SPDX-License-Identifier: Apache-2.0
 */

<template>
  <div class="flex items-center justify-center min-h-[60vh]">
    <div class="card w-full max-w-2xl bg-base-100 shadow-xl">
      <div class="card-body text-center">
        <div class="flex justify-center mb-6">
          <img src="/tk_full_logo.svg" alt="Thinkube" class="h-32" />
        </div>
        
        <h1 class="text-4xl font-bold mb-4 text-base-content">Welcome!</h1>
        <p class="text-lg text-base-content text-opacity-80 mb-8">
          Let's set up your AI-focused Kubernetes homelab platform
        </p>
        
        <div class="alert alert-info mb-8">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="stroke-current shrink-0 w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
          </svg>
          <span class="text-base-content">This installer will guide you through configuring and deploying Thinkube on your Ubuntu systems.</span>
        </div>

        <div class="prose prose-base max-w-none text-left mb-8">
          <ul class="space-y-3 list-none">
            <li class="flex items-center gap-3">
              <svg class="w-6 h-6 text-success flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
              </svg>
              <span class="font-medium text-base-content">System requirements check</span>
            </li>
            <li class="flex items-center gap-3">
              <svg class="w-6 h-6 text-success flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
              </svg>
              <span class="font-medium text-base-content">Cluster configuration</span>
            </li>
            <li class="flex items-center gap-3">
              <svg class="w-6 h-6 text-success flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
              </svg>
              <span class="font-medium text-base-content">Automated deployment</span>
            </li>
          </ul>
        </div>

        <div class="card-actions justify-center">
          <button class="btn btn-primary btn-lg gap-2" @click="$router.push('/requirements')">
            Get Started
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
            </svg>
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
// Welcome screen - no automatic navigation logic
// User must explicitly click "Get Started" to proceed

// 🤖 AI-generated
</script>

// frontend/src/pages/welcome.tsx
/*
 * Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
 * SPDX-License-Identifier: Apache-2.0
 */

import { useNavigate } from "react-router-dom"
import { TkCard, TkCardContent, TkCardFooter, TkCardHeader } from "thinkube-style/components/cards-data"
import { TkAlert, TkAlertDescription } from "thinkube-style/components/feedback"
import { TkButton } from "thinkube-style/components/buttons-badges"
import { Info, CheckCircle2, ChevronRight } from "lucide-react"

export default function Welcome() {
  const navigate = useNavigate()

  return (
    <div className="max-w-7xl mx-auto px-6 py-8 flex items-center justify-center h-full">
      <div className="w-full flex items-center justify-center">
        <TkCard className="max-w-2xl w-full shadow-xl">
          <TkCardHeader className="text-center">
            <div className="flex justify-center mb-6">
              <img
                src="/tk_full_logo.svg"
                alt="Thinkube"
                className="h-32 w-auto"
              />
            </div>

            <h1 className="text-4xl font-heading font-bold mb-2">Welcome</h1>

            <p className="text-lg text-muted-foreground mb-8">
              Let's set up your AI-focused Kubernetes homelab platform
            </p>
          </TkCardHeader>

          <TkCardContent className="space-y-8">
            <TkAlert className="bg-info/10 text-info border-info/20">
              <Info className="h-4 w-4" />
              <TkAlertDescription>
                This installer will guide you through configuring and deploying Thinkube on your Ubuntu systems.
              </TkAlertDescription>
            </TkAlert>

            <div className="space-y-3 text-left">
              <div className="flex items-center gap-3">
                <CheckCircle2 className="h-6 w-6 text-success flex-shrink-0" />
                <span className="font-medium">System requirements check</span>
              </div>
              <div className="flex items-center gap-3">
                <CheckCircle2 className="h-6 w-6 text-success flex-shrink-0" />
                <span className="font-medium">Cluster configuration</span>
              </div>
              <div className="flex items-center gap-3">
                <CheckCircle2 className="h-6 w-6 text-success flex-shrink-0" />
                <span className="font-medium">Automated deployment</span>
              </div>
            </div>
          </TkCardContent>

          <TkCardFooter className="justify-center">
            <TkButton
              size="lg"
              className="gap-2"
              onClick={() => navigate('/requirements')}
            >
              Get Started
              <ChevronRight className="h-5 w-5" />
            </TkButton>
          </TkCardFooter>
        </TkCard>
      </div>
    </div>
  )
}
