// frontend/src/pages/deploy.tsx
/*
 * Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
 * SPDX-License-Identifier: Apache-2.0
 */

import { useReducer, useEffect, useRef } from "react"
import { useNavigate } from "react-router-dom"
import { TkCard, TkCardContent } from "thinkube-style/components/cards-data"
import { TkButton } from "thinkube-style/components/buttons-badges"
import { TkAlert, TkAlertDescription, tkToast } from "thinkube-style/components/feedback"
import { TkSubwayProgress } from "thinkube-style/components/progress"
import { PlaybookExecutorStream } from "@/components/PlaybookExecutorStream"
import { AlertCircle, Download, Copy, PartyPopper } from "lucide-react"

// Types
interface Playbook {
  id: string
  phase: string
  title: string
  name: string
  extraVars?: Record<string, any>
}

interface PlaybookLog {
  status: 'success' | 'failed' | 'running'
  logs: string
  timestamp: Date
}

interface DeployState {
  queue: Playbook[]
  currentIndex: number
  status: 'idle' | 'running' | 'failed' | 'complete'
  logs: Map<string, PlaybookLog>
  error: string | null
  failedPlaybook: Playbook | null
  // Pre-rollback state for restoration
  preRollbackQueue: Playbook[] | null
  preRollbackIndex: number | null
  preRollbackError: string | null
}

type DeployAction =
  | { type: 'INIT_QUEUE'; queue: Playbook[]; savePreRollbackState?: boolean }
  | { type: 'START_PLAYBOOK'; index: number }
  | { type: 'PLAYBOOK_SUCCESS'; playbookId: string; logs: string }
  | { type: 'PLAYBOOK_FAILED'; playbookId: string; logs: string; error: string }
  | { type: 'COMPLETE' }
  | { type: 'RESET' }
  | { type: 'RESTORE_AFTER_ROLLBACK' }

// Reducer
function deployReducer(state: DeployState, action: DeployAction): DeployState {
  switch (action.type) {
    case 'INIT_QUEUE':
      // If savePreRollbackState is true, save the current state for restoration
      if (action.savePreRollbackState) {
        return {
          ...state,
          queue: action.queue,
          status: 'idle',
          preRollbackQueue: state.queue,
          preRollbackIndex: state.currentIndex,
          preRollbackError: state.error
        }
      }
      return { ...state, queue: action.queue, status: 'idle' }

    case 'START_PLAYBOOK':
      return { ...state, currentIndex: action.index, status: 'running', error: null }

    case 'PLAYBOOK_SUCCESS': {
      const newLogs = new Map(state.logs)
      newLogs.set(action.playbookId, {
        status: 'success',
        logs: action.logs,
        timestamp: new Date()
      })
      return { ...state, logs: newLogs }
    }

    case 'PLAYBOOK_FAILED': {
      const newLogs = new Map(state.logs)
      newLogs.set(action.playbookId, {
        status: 'failed',
        logs: action.logs,
        timestamp: new Date()
      })
      return {
        ...state,
        logs: newLogs,
        status: 'failed',
        error: action.error,
        failedPlaybook: state.queue[state.currentIndex]
      }
    }

    case 'COMPLETE':
      return { ...state, status: 'complete', currentIndex: state.queue.length }

    case 'RESET':
      return {
        queue: [],
        currentIndex: 0,
        status: 'idle',
        logs: new Map(),
        error: null,
        failedPlaybook: null,
        preRollbackQueue: null,
        preRollbackIndex: null,
        preRollbackError: null
      }

    case 'RESTORE_AFTER_ROLLBACK':
      // Restore the pre-rollback state to show error UI with retry/rollback buttons
      if (state.preRollbackQueue && state.preRollbackIndex !== null) {
        return {
          ...state,
          queue: state.preRollbackQueue,
          currentIndex: state.preRollbackIndex,
          status: 'failed',
          error: state.preRollbackError,
          failedPlaybook: state.preRollbackQueue[state.preRollbackIndex],
          preRollbackQueue: null,
          preRollbackIndex: null,
          preRollbackError: null
        }
      }
      return state

    default:
      return state
  }
}

const initialState: DeployState = {
  queue: [],
  currentIndex: 0,
  status: 'idle',
  logs: new Map(),
  error: null,
  failedPlaybook: null,
  preRollbackQueue: null,
  preRollbackIndex: null,
  preRollbackError: null
}

export default function Deploy() {
  const navigate = useNavigate()
  const [state, dispatch] = useReducer(deployReducer, initialState)
  const executorRef = useRef<any>(null)
  const currentLogsRef = useRef<string>('')

  // Build playbook queue
  const buildQueue = async (): Promise<Playbook[]> => {
    const queue: Playbook[] = []
    const config = typeof window !== 'undefined'
      ? JSON.parse(localStorage.getItem('thinkube-config') || '{}')
      : {}

    // Phase 1: Initial Setup
    queue.push({
      id: 'env-setup',
      phase: 'initial',
      title: 'Setting up Environment',
      name: 'ansible/00_initial_setup/20_setup_env.yaml'
    })

    queue.push({
      id: 'python-setup',
      phase: 'initial',
      title: 'Setting up Python Virtual Environments',
      name: 'ansible/40_thinkube/core/infrastructure/00_setup_python_k8s.yaml'
    })

    queue.push({
      id: 'github-cli',
      phase: 'initial',
      title: 'Setting up GitHub CLI',
      name: 'ansible/00_initial_setup/40_setup_github_cli.yaml'
    })

    // Phase 2: Networking
    const networkMode = config.networkMode || 'overlay'
    const overlayProvider = config.overlayProvider || 'zerotier'

    if (networkMode === 'overlay') {
      if (overlayProvider === 'zerotier') {
        queue.push({
          id: 'zerotier-setup',
          phase: 'initial',
          title: 'Configuring ZeroTier Overlay Network',
          name: 'ansible/30_networking/10_setup_zerotier.yaml'
        })
      } else if (overlayProvider === 'tailscale') {
        queue.push({
          id: 'tailscale-setup',
          phase: 'initial',
          title: 'Configuring Tailscale Overlay Network',
          name: 'ansible/30_networking/11_setup_tailscale.yaml'
        })
      }
    }

    // Phase 3: Kubernetes Infrastructure
    queue.push({
      id: 'setup-python-k8s',
      phase: 'kubernetes',
      title: 'Setting up Python Kubernetes Libraries',
      name: 'ansible/40_thinkube/core/infrastructure/00_setup_python_k8s.yaml'
    })

    queue.push({
      id: 'k8s',
      phase: 'kubernetes',
      title: 'Installing Canonical Kubernetes',
      name: 'ansible/40_thinkube/core/infrastructure/k8s/10_install_k8s.yaml'
    })

    // Join worker nodes
    const clusterNodes = typeof window !== 'undefined'
      ? JSON.parse(sessionStorage.getItem('clusterNodes') || '[]')
      : []
    const hasWorkers = clusterNodes.some((n: any) => n.role === 'worker')
    if (hasWorkers) {
      queue.push({
        id: 'k8s-join-workers',
        phase: 'kubernetes',
        title: 'Joining Worker Nodes to Cluster',
        name: 'ansible/40_thinkube/core/infrastructure/k8s/20_join_workers.yaml'
      })
    }

    // GPU operator if needed
    const serverHardware = typeof window !== 'undefined'
      ? JSON.parse(sessionStorage.getItem('serverHardware') || '[]')
      : []
    const needsGPUOperator = serverHardware.some((s: any) => s.hardware?.gpu_detected)
    if (needsGPUOperator) {
      queue.push({
        id: 'gpu-operator',
        phase: 'kubernetes',
        title: 'Installing NVIDIA GPU Operator',
        name: 'ansible/40_thinkube/core/infrastructure/gpu_operator/00_install.yaml'
      })
    }

    queue.push({
      id: 'dns-server',
      phase: 'kubernetes',
      title: 'Deploying DNS Server (BIND9)',
      name: 'ansible/40_thinkube/core/infrastructure/dns-server/10_deploy.yaml'
    })

    queue.push({
      id: 'coredns',
      phase: 'kubernetes',
      title: 'Deploying CoreDNS',
      name: 'ansible/40_thinkube/core/infrastructure/coredns/10_deploy.yaml'
    })

    queue.push({
      id: 'coredns-configure-nodes',
      phase: 'kubernetes',
      title: 'Configuring Node DNS',
      name: 'ansible/40_thinkube/core/infrastructure/coredns/15_configure_node_dns.yaml'
    })

    queue.push({
      id: 'acme-certificates',
      phase: 'kubernetes',
      title: 'Setting up SSL Certificates',
      name: 'ansible/40_thinkube/core/infrastructure/acme-certificates/10_deploy.yaml'
    })

    queue.push({
      id: 'ingress',
      phase: 'kubernetes',
      title: 'Deploying Ingress Controller',
      name: 'ansible/40_thinkube/core/infrastructure/ingress/10_deploy.yaml'
    })

    // Core Services
    queue.push({
      id: 'postgresql',
      phase: 'kubernetes',
      title: 'Installing PostgreSQL',
      name: 'ansible/40_thinkube/core/postgresql/00_install.yaml'
    })

    queue.push({
      id: 'keycloak',
      phase: 'kubernetes',
      title: 'Installing Keycloak',
      name: 'ansible/40_thinkube/core/keycloak/00_install.yaml'
    })

    queue.push({
      id: 'harbor',
      phase: 'kubernetes',
      title: 'Installing Harbor',
      name: 'ansible/40_thinkube/core/harbor/00_install.yaml'
    })

    queue.push({
      id: 'seaweedfs',
      phase: 'kubernetes',
      title: 'Installing SeaweedFS',
      name: 'ansible/40_thinkube/core/seaweedfs/00_install.yaml'
    })

    queue.push({
      id: 'juicefs',
      phase: 'kubernetes',
      title: 'Installing JuiceFS Distributed Filesystem',
      name: 'ansible/40_thinkube/core/juicefs/00_install.yaml'
    })

    queue.push({
      id: 'argo-workflows',
      phase: 'kubernetes',
      title: 'Installing Argo Workflows',
      name: 'ansible/40_thinkube/core/argo-workflows/00_install.yaml'
    })

    queue.push({
      id: 'argocd',
      phase: 'kubernetes',
      title: 'Installing ArgoCD',
      name: 'ansible/40_thinkube/core/argocd/00_install.yaml'
    })

    queue.push({
      id: 'devpi',
      phase: 'kubernetes',
      title: 'Installing DevPi',
      name: 'ansible/40_thinkube/core/devpi/00_install.yaml'
    })

    queue.push({
      id: 'gitea',
      phase: 'kubernetes',
      title: 'Installing Gitea',
      name: 'ansible/40_thinkube/core/gitea/00_install.yaml'
    })

    queue.push({
      id: 'code-server',
      phase: 'kubernetes',
      title: 'Installing Code-Server',
      name: 'ansible/40_thinkube/core/code-server/00_install.yaml'
    })

    queue.push({
      id: 'thinkube-control',
      phase: 'kubernetes',
      title: 'Deploying Thinkube Control',
      name: 'ansible/40_thinkube/core/thinkube-control/00_install.yaml'
    })

    return queue
  }

  // Execute playbook
  const executePlaybook = (playbook: Playbook) => {
    if (!executorRef.current?.startExecution) return

    const sudoPassword = sessionStorage.getItem('sudoPassword')

    executorRef.current.startExecution({
      environment: {
        ANSIBLE_BECOME_PASSWORD: sudoPassword,
        ANSIBLE_SSH_PASSWORD: sudoPassword
      },
      extra_vars: playbook.extraVars || {}
    })
  }

  // Handle playbook completion
  const handlePlaybookComplete = (result: any) => {
    const currentPlaybook = state.queue[state.currentIndex]
    if (!currentPlaybook) return

    // Extract logs from result or use ref
    const logs = result.logs || result.output || currentLogsRef.current

    // Check if this is a rollback playbook
    const isRollback = currentPlaybook.phase === 'rollback' || currentPlaybook.id.startsWith('rollback-')

    if (result.status === 'error' || result.status === 'failed') {
      // For rollback failures, record the log and restore pre-rollback state
      if (isRollback) {
        dispatch({
          type: 'PLAYBOOK_SUCCESS',
          playbookId: currentPlaybook.id,
          logs
        })
        // Restore the failed deployment state to show retry/rollback buttons
        setTimeout(() => {
          dispatch({ type: 'RESTORE_AFTER_ROLLBACK' })
        }, 100)
      } else {
        dispatch({
          type: 'PLAYBOOK_FAILED',
          playbookId: currentPlaybook.id,
          logs,
          error: result.message || 'Playbook execution failed'
        })
      }
    } else {
      dispatch({
        type: 'PLAYBOOK_SUCCESS',
        playbookId: currentPlaybook.id,
        logs
      })

      // For rollback success, restore pre-rollback state to show retry/rollback buttons
      if (isRollback) {
        setTimeout(() => {
          dispatch({ type: 'RESTORE_AFTER_ROLLBACK' })
        }, 100)
      } else {
        // Auto-continue to next playbook for normal deployment
        const nextIndex = state.currentIndex + 1
        if (nextIndex < state.queue.length) {
          setTimeout(() => {
            dispatch({ type: 'START_PLAYBOOK', index: nextIndex })
          }, 100)
        } else {
          dispatch({ type: 'COMPLETE' })
        }
      }
    }
  }

  // Retry failed playbook
  const handleRetry = () => {
    if (state.failedPlaybook) {
      dispatch({ type: 'START_PLAYBOOK', index: state.currentIndex })
    }
  }

  // Rollback mapping: deployment playbook id -> rollback playbook path
  const getRollbackPlaybook = (deploymentId: string): string | null => {
    const rollbackMap: Record<string, string> = {
      // Initial setup - no rollback
      'env-setup': null,
      'python-setup': null,
      'github-cli': null,
      'zerotier-setup': null,
      'tailscale-setup': null,

      // Kubernetes infrastructure
      'setup-python-k8s': null,
      'k8s': 'ansible/40_thinkube/core/infrastructure/k8s/19_rollback_control.yaml',
      'k8s-join-workers': 'ansible/40_thinkube/core/infrastructure/k8s/29_rollback_workers.yaml',
      'gpu-operator': 'ansible/40_thinkube/core/infrastructure/gpu_operator/19_rollback.yaml',
      'dns-server': 'ansible/40_thinkube/core/infrastructure/dns-server/19_rollback.yaml',
      'coredns': 'ansible/40_thinkube/core/infrastructure/coredns/19_rollback.yaml',
      'coredns-configure-nodes': null,
      'acme-certificates': 'ansible/40_thinkube/core/infrastructure/acme-certificates/19_rollback.yaml',
      'ingress': 'ansible/40_thinkube/core/infrastructure/ingress/19_rollback.yaml',

      // Core services
      'postgresql': 'ansible/40_thinkube/core/postgresql/19_rollback.yaml',
      'keycloak': 'ansible/40_thinkube/core/keycloak/19_rollback.yaml',
      'harbor': 'ansible/40_thinkube/core/harbor/19_rollback.yaml',
      'seaweedfs': 'ansible/40_thinkube/core/seaweedfs/19_rollback.yaml',
      'juicefs': 'ansible/40_thinkube/core/juicefs/19_rollback.yaml',
      'argo-workflows': 'ansible/40_thinkube/core/argo-workflows/19_rollback.yaml',
      'argocd': 'ansible/40_thinkube/core/argocd/19_rollback.yaml',
      'devpi': 'ansible/40_thinkube/core/devpi/19_rollback.yaml',
      'gitea': 'ansible/40_thinkube/core/gitea/19_rollback.yaml',
      'code-server': 'ansible/40_thinkube/core/code-server/19_rollback.yaml',
      'thinkube-control': 'ansible/40_thinkube/core/thinkube-control/19_rollback.yaml'
    }

    return rollbackMap[deploymentId] || null
  }

  // Rollback
  const handleRollback = () => {
    // Rollback only the single failed component at currentIndex
    const playbook = state.queue[state.currentIndex]
    if (!playbook) {
      console.log('No component at currentIndex to rollback')
      return
    }

    const logEntry = state.logs.get(playbook.id)

    // Only rollback if component was attempted (failed status)
    if (!logEntry || logEntry.status !== 'failed') {
      console.log('Component was not failed, nothing to rollback')
      return
    }

    const rollbackPath = getRollbackPlaybook(playbook.id)
    if (!rollbackPath) {
      console.log('No rollback playbook found for', playbook.id)
      return
    }

    // Execute single rollback playbook
    const rollbackQueue: Playbook[] = [{
      id: `rollback-${playbook.id}`,
      phase: 'rollback',
      title: `Rolling back ${playbook.title}`,
      name: rollbackPath
    }]

    // Save pre-rollback state so we can restore it after rollback completes
    dispatch({ type: 'INIT_QUEUE', queue: rollbackQueue, savePreRollbackState: true })
    dispatch({ type: 'START_PLAYBOOK', index: 0 })
  }

  // Download all logs
  const downloadLogs = () => {
    if (state.logs.size === 0) {
      tkToast.error('No logs available to download')
      return
    }

    let allLogs = ''
    state.logs.forEach((log, playbookId) => {
      allLogs += `\n\n=== ${playbookId} (${log.status}) ===\n`
      allLogs += `Timestamp: ${log.timestamp.toISOString()}\n`
      allLogs += log.logs
    })

    if (!allLogs.trim()) {
      tkToast.error('Logs are empty')
      return
    }

    const blob = new Blob([allLogs], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `thinkube-deploy-logs-${new Date().toISOString()}.txt`
    a.click()
    URL.revokeObjectURL(url)
    tkToast.success('Logs downloaded successfully!')
  }

  // Initialize on mount
  useEffect(() => {
    const init = async () => {
      const queue = await buildQueue()
      dispatch({ type: 'INIT_QUEUE', queue })
      // Auto-start first playbook
      setTimeout(() => {
        dispatch({ type: 'START_PLAYBOOK', index: 0 })
      }, 500)
    }
    init()
  }, [])

  // Execute playbook when index changes
  useEffect(() => {
    if (state.status === 'running' && state.queue[state.currentIndex]) {
      const playbook = state.queue[state.currentIndex]
      currentLogsRef.current = '' // Reset logs for new playbook
      setTimeout(() => executePlaybook(playbook), 200)
    }
  }, [state.currentIndex, state.status])

  // Derive subway steps - use playbook titles + final "Complete" step
  const playbookTitles = [...state.queue.map(p => p.title), 'Deployment Complete']
  const currentPlaybookNumber = state.status === 'complete'
    ? state.queue.length + 1
    : state.currentIndex + 1

  // Copy logs to clipboard
  const copyLogs = () => {
    let allLogs = ''
    state.logs.forEach((log, playbookId) => {
      allLogs += `\n\n=== ${playbookId} (${log.status}) ===\n`
      allLogs += `Timestamp: ${log.timestamp.toISOString()}\n`
      allLogs += log.logs
    })

    navigator.clipboard.writeText(allLogs)
      .then(() => tkToast.success('All logs copied to clipboard!'))
      .catch(err => tkToast.error('Failed to copy logs: ' + err))
  }

  // Copy only the failed playbook logs
  const copyFailedLog = () => {
    if (!state.failedPlaybook) {
      tkToast.error('No failed playbook found')
      return
    }

    const log = state.logs.get(state.failedPlaybook.id)
    if (!log) {
      tkToast.error(`No log found for playbook: ${state.failedPlaybook.id}`)
      console.error('Available log keys:', Array.from(state.logs.keys()))
      console.error('Looking for:', state.failedPlaybook.id)
      return
    }

    if (!log.logs || !log.logs.trim()) {
      tkToast.error('Failed playbook log is empty')
      return
    }

    const failedLog = `=== ${state.failedPlaybook.title} (FAILED) ===
Playbook ID: ${state.failedPlaybook.id}
Timestamp: ${log.timestamp.toISOString()}
Error: ${state.error}

${log.logs}`

    navigator.clipboard.writeText(failedLog)
      .then(() => tkToast.success('Failed playbook log copied to clipboard!'))
      .catch(err => tkToast.error('Failed to copy log: ' + err))
  }

  return (
    <div className="container mx-auto px-6 py-8">
      <div className="mb-6">
        <h1 className="text-3xl font-bold">Deploying Thinkube Infrastructure</h1>
      </div>

      {/* Subway Progress */}
      <TkCard className="mb-6">
        <TkCardContent className="pt-6">
          <TkSubwayProgress
            steps={playbookTitles}
            current={currentPlaybookNumber}
            isRunning={state.status === 'running'}
          />
        </TkCardContent>
      </TkCard>

      {/* Current Playbook Execution (inline) */}
      {state.status === 'running' && state.queue[state.currentIndex] && (
        <TkCard className="mb-6">
          <TkCardContent className="pt-6">
            <h2 className="text-xl font-semibold mb-4">
              {state.queue[state.currentIndex].title}
            </h2>
            <PlaybookExecutorStream
              ref={executorRef}
              title={state.queue[state.currentIndex].title}
              playbookName={state.queue[state.currentIndex].name}
              onComplete={handlePlaybookComplete}
            />
          </TkCardContent>
        </TkCard>
      )}

      {/* Error State */}
      {state.status === 'failed' && (
        <TkAlert variant="destructive" className="mb-6">
          <AlertCircle className="h-4 w-4" />
          <TkAlertDescription>
            <div className="mb-4">
              <strong>Deployment Failed</strong>
              <p>{state.error}</p>
              <p className="text-sm mt-2">Failed at: {state.failedPlaybook?.title}</p>
            </div>
            <div className="flex gap-2">
              <TkButton size="sm" onClick={handleRetry}>
                Retry
              </TkButton>
              <TkButton size="sm" variant="outline" onClick={handleRollback}>
                Rollback
              </TkButton>
              <TkButton size="sm" variant="ghost" onClick={copyFailedLog}>
                <Copy className="w-4 h-4 mr-2" />
                Copy Failed Log
              </TkButton>
              <TkButton size="sm" variant="ghost" onClick={downloadLogs}>
                <Download className="w-4 h-4 mr-2" />
                Download All Logs
              </TkButton>
            </div>
          </TkAlertDescription>
        </TkAlert>
      )}

      {/* Complete State */}
      {state.status === 'complete' && (
        <TkCard className="mb-6">
          <TkCardContent className="pt-6 text-center">
            <PartyPopper className="w-24 h-24 text-teal-500 mb-6 mx-auto" />
            <h2 className="text-2xl font-bold mb-4">Deployment Complete!</h2>
            <p className="mb-6">Your Thinkube infrastructure has been successfully deployed.</p>
            <div className="flex justify-center gap-2">
              <TkButton onClick={() => navigate('/complete')}>
                View Cluster Details
              </TkButton>
              <TkButton variant="outline" onClick={copyLogs}>
                <Copy className="w-4 h-4 mr-2" />
                Copy Logs
              </TkButton>
              <TkButton variant="outline" onClick={downloadLogs}>
                <Download className="w-4 h-4 mr-2" />
                Download Logs
              </TkButton>
            </div>
          </TkCardContent>
        </TkCard>
      )}
    </div>
  )
}

// frontend/src/views/Deploy.vue
/*
 * Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
 * SPDX-License-Identifier: Apache-2.0
 */

<template>
  <div class="max-w-6xl mx-auto">
    <div class="flex justify-between items-center mb-6">
      <h1 class="text-3xl font-bold">Deploying Thinkube Infrastructure</h1>
      <button
        class="btn btn-ghost btn-sm gap-2"
        @click="resetDeployment"
        title="Start over from configuration"
      >
        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"></path>
        </svg>
        Reset
      </button>
    </div>

    <!-- Deployment Progress Overview -->
    <div class="card bg-base-100 shadow-xl mb-6">
      <div class="card-body">
        <h2 class="card-title mb-4">Deployment Progress</h2>

        <!-- Phase Indicators -->
        <div class="flex flex-wrap gap-2 mb-6">
          <div v-for="(phase, index) in deploymentPhases" :key="phase.id"
               class="badge gap-2"
               :class="getPhaseClass(phase)">
            <svg v-if="phase.status === 'completed'" class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
            </svg>
            <svg v-else-if="phase.status === 'active'" class="w-4 h-4 animate-spin" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
              <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
            {{ phase.name }}
          </div>
        </div>

        <progress class="progress progress-primary w-full" :value="overallProgress" max="100"></progress>
        <p class="text-sm text-center mt-2">{{ completedPlaybooks }} / {{ totalPlaybooks }} playbooks ({{ overallProgress }}%)</p>
      </div>
    </div>

    <!-- Current Playbook Execution -->
    <div v-if="currentPlaybook">
      <PlaybookExecutorStream
        ref="currentPlaybookExecutor"
        :key="currentPlaybook.id"
        :title="currentPlaybook.title"
        :playbook-name="currentPlaybook.name"
        :extra-vars="currentPlaybook.extraVars"
        :test-mode="testMode"
        :on-retry="retryCurrentPlaybook"
        @complete="handlePlaybookComplete"
        @continue="handlePlaybookContinue"
      />
    </div>

    <!-- Test Mode Control Buttons -->
    <div v-if="testMode && !currentPlaybook && !deploymentComplete" class="card bg-base-100 shadow-xl mb-6">
      <div class="card-body">
        <h2 class="card-title">🧪 Test Mode Controls</h2>
        <div class="flex gap-2">
          <button
            class="btn btn-primary"
            @click="handlePlaybookContinue"
            :disabled="!canContinue"
          >
            Next Playbook
          </button>
          <button
            class="btn btn-info"
            @click="runTestPlaybook"
          >
            Run Test (18)
          </button>
          <button
            class="btn btn-warning"
            @click="runRollbackPlaybook"
          >
            Rollback (19)
          </button>
        </div>
      </div>
    </div>

    <!-- Completion -->
    <div v-if="deploymentComplete" class="card bg-base-100 shadow-xl">
      <div class="card-body text-center">
        <div class="text-6xl mb-4">🎉</div>
        <h2 class="card-title justify-center mb-4">Deployment Complete!</h2>
        <p class="mb-6">Your Thinkube infrastructure has been successfully deployed.</p>
        <button
          class="btn btn-primary btn-lg gap-2"
          @click="$router.push('/complete')"
        >
          View Cluster Details
          <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7l5 5m0 0l-5 5m5-5H6"></path>
          </svg>
        </button>
      </div>
    </div>

    <!-- Error State -->
    <div v-if="deploymentError" class="alert alert-error">
      <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
      <div>
        <h3 class="font-bold">Deployment Failed</h3>
        <p>{{ deploymentError }}</p>
        <div class="flex gap-2 mt-2">
          <button class="btn btn-sm btn-outline" @click="retryCurrentPlaybook">Retry</button>
          <button class="btn btn-sm btn-ghost" @click="resetDeployment">Reset & Start Over</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, nextTick } from 'vue'
import { useRouter } from 'vue-router'
import PlaybookExecutorStream from '@/components/PlaybookExecutorStream.vue'
import { isTestMode, shouldEnableShellConfig } from '@/utils/configFlags'

const router = useRouter()

// Deployment phases
const deploymentPhases = ref([
  { id: 'initial', name: 'Initial Setup', status: 'pending' },
  { id: 'kubernetes', name: 'Kubernetes', status: 'pending' }
])

// In-memory state (no persistence)
const playbookQueue = ref([])
const currentPlaybookIndex = ref(0)
const completedPlaybooks = ref(0)
const totalPlaybooks = ref(0)

// State variables
const currentPlaybook = ref(null)
const currentPhase = ref(null)
const deploymentComplete = ref(false)
const deploymentError = ref('')
const testMode = ref(false)

// Component refs
const currentPlaybookExecutor = ref(null)

// Progress tracking
const overallProgress = computed(() => {
  if (totalPlaybooks.value === 0) return 0
  return Math.round((completedPlaybooks.value / totalPlaybooks.value) * 100)
})

// Update phase statuses based on current playbook
const updatePhaseStatuses = () => {
  // Reset all phases to pending
  deploymentPhases.value.forEach(phase => {
    phase.status = 'pending'
  })

  // Mark completed phases
  const currentIdx = currentPlaybookIndex.value
  const queue = playbookQueue.value

  for (let i = 0; i < currentIdx && i < queue.length; i++) {
    const playbook = queue[i]
    const phase = deploymentPhases.value.find(p => p.id === playbook.phase)
    if (phase) {
      phase.status = 'completed'
    }
  }

  // Mark current phase as active
  if (currentPhase.value) {
    const phase = deploymentPhases.value.find(p => p.id === currentPhase.value)
    if (phase && phase.status === 'pending') {
      phase.status = 'active'
    }
  }
}

// Get phase class for styling
const getPhaseClass = (phase) => {
  switch (phase.status) {
    case 'completed': return 'badge-success'
    case 'active': return 'badge-warning'
    case 'failed': return 'badge-error'
    default: return 'badge-ghost'
  }
}

// Build playbook queue based on deployment type
const buildPlaybookQueue = async () => {
  const queue = []
  console.log('Building playbook queue...')

  // Load config from localStorage
  const config = JSON.parse(localStorage.getItem('thinkube-config') || '{}')

  // Phase 1: Initial Setup
  queue.push({
    id: 'env-setup',
    phase: 'initial',
    title: 'Setting up Environment',
    name: 'ansible/00_initial_setup/20_setup_env.yaml'
  })

  queue.push({
    id: 'python-setup',
    phase: 'initial',
    title: 'Setting up Python Virtual Environments',
    name: 'ansible/40_thinkube/core/infrastructure/00_setup_python_k8s.yaml'
  })

  // Add shell configuration (optional, controlled by TK_SHELL_CONFIG=1)
  const enableShellConfig = await shouldEnableShellConfig()
  console.log('🔍 DEBUG enableShellConfig:', enableShellConfig)
  if (enableShellConfig) {
    console.log('✅ Adding shell-setup playbook to queue')
    queue.push({
      id: 'shell-setup',
      phase: 'initial',
      title: 'Configuring Shell Environments',
      name: 'ansible/misc/00_setup_shells.yml'
    })
  } else {
    console.log('⏭️  Skipping shell-setup playbook')
  }

  queue.push({
    id: 'github-cli',
    phase: 'initial',
    title: 'Setting up GitHub CLI',
    name: 'ansible/00_initial_setup/40_setup_github_cli.yaml'
  })

  // Phase 2: Networking
  const networkMode = config.networkMode || 'overlay'
  const overlayProvider = config.overlayProvider || 'zerotier'

  if (networkMode === 'overlay') {
    if (overlayProvider === 'zerotier') {
      queue.push({
        id: 'zerotier-setup',
        phase: 'initial',
        title: 'Configuring ZeroTier Overlay Network',
        name: 'ansible/30_networking/10_setup_zerotier.yaml'
      })
    } else if (overlayProvider === 'tailscale') {
      queue.push({
        id: 'tailscale-setup',
        phase: 'initial',
        title: 'Configuring Tailscale Overlay Network',
        name: 'ansible/30_networking/11_setup_tailscale.yaml'
      })
    }
  }

  // Phase 3: Kubernetes Infrastructure
  queue.push({
    id: 'setup-python-k8s',
    phase: 'kubernetes',
    title: 'Setting up Python Kubernetes Libraries',
    name: 'ansible/40_thinkube/core/infrastructure/00_setup_python_k8s.yaml'
  })

  queue.push({
    id: 'k8s',
    phase: 'kubernetes',
    title: 'Installing Canonical Kubernetes',
    name: 'ansible/40_thinkube/core/infrastructure/k8s/10_install_k8s.yaml'
  })

  // Join worker nodes
  const clusterNodes = JSON.parse(sessionStorage.getItem('clusterNodes') || '[]')
  const hasWorkers = clusterNodes.some(n => n.role === 'worker')
  if (hasWorkers) {
    queue.push({
      id: 'k8s-join-workers',
      phase: 'kubernetes',
      title: 'Joining Worker Nodes to Cluster',
      name: 'ansible/40_thinkube/core/infrastructure/k8s/20_join_workers.yaml'
    })
  }

  // GPU operator if needed
  const serverHardware = JSON.parse(sessionStorage.getItem('serverHardware') || '[]')
  const needsGPUOperator = serverHardware.some(s => s.hardware?.gpu_detected)
  if (needsGPUOperator) {
    queue.push({
      id: 'gpu-operator',
      phase: 'kubernetes',
      title: 'Installing NVIDIA GPU Operator',
      name: 'ansible/40_thinkube/core/infrastructure/gpu_operator/10_deploy.yaml'
    })
  }

  queue.push({
    id: 'dns-server',
    phase: 'kubernetes',
    title: 'Deploying DNS Server (BIND9)',
    name: 'ansible/40_thinkube/core/infrastructure/dns-server/10_deploy.yaml'
  })

  queue.push({
    id: 'coredns',
    phase: 'kubernetes',
    title: 'Deploying CoreDNS',
    name: 'ansible/40_thinkube/core/infrastructure/coredns/10_deploy.yaml'
  })

  queue.push({
    id: 'coredns-configure-nodes',
    phase: 'kubernetes',
    title: 'Configuring Node DNS',
    name: 'ansible/40_thinkube/core/infrastructure/coredns/15_configure_node_dns.yaml'
  })

  queue.push({
    id: 'acme-certificates',
    phase: 'kubernetes',
    title: 'Setting up SSL Certificates',
    name: 'ansible/40_thinkube/core/infrastructure/acme-certificates/10_deploy.yaml'
  })

  queue.push({
    id: 'ingress',
    phase: 'kubernetes',
    title: 'Deploying Ingress Controller',
    name: 'ansible/40_thinkube/core/infrastructure/ingress/10_deploy.yaml'
  })

  // Core Services
  queue.push({
    id: 'postgresql',
    phase: 'kubernetes',
    title: 'Installing PostgreSQL',
    name: 'ansible/40_thinkube/core/postgresql/00_install.yaml'
  })

  queue.push({
    id: 'keycloak',
    phase: 'kubernetes',
    title: 'Installing Keycloak',
    name: 'ansible/40_thinkube/core/keycloak/00_install.yaml'
  })

  queue.push({
    id: 'harbor',
    phase: 'kubernetes',
    title: 'Installing Harbor',
    name: 'ansible/40_thinkube/core/harbor/00_install.yaml'
  })

  queue.push({
    id: 'seaweedfs',
    phase: 'kubernetes',
    title: 'Installing SeaweedFS',
    name: 'ansible/40_thinkube/core/seaweedfs/00_install.yaml'
  })

  queue.push({
    id: 'juicefs',
    phase: 'kubernetes',
    title: 'Installing JuiceFS Distributed Filesystem',
    name: 'ansible/40_thinkube/core/juicefs/00_install.yaml'
  })

  queue.push({
    id: 'argo-workflows',
    phase: 'kubernetes',
    title: 'Installing Argo Workflows',
    name: 'ansible/40_thinkube/core/argo-workflows/00_install.yaml'
  })

  queue.push({
    id: 'argocd',
    phase: 'kubernetes',
    title: 'Installing ArgoCD',
    name: 'ansible/40_thinkube/core/argocd/00_install.yaml'
  })

  queue.push({
    id: 'devpi',
    phase: 'kubernetes',
    title: 'Installing DevPi',
    name: 'ansible/40_thinkube/core/devpi/00_install.yaml'
  })

  queue.push({
    id: 'gitea',
    phase: 'kubernetes',
    title: 'Installing Gitea',
    name: 'ansible/40_thinkube/core/gitea/00_install.yaml'
  })

  queue.push({
    id: 'code-server',
    phase: 'kubernetes',
    title: 'Installing Code-Server',
    name: 'ansible/40_thinkube/core/code-server/00_install.yaml'
  })

  queue.push({
    id: 'thinkube-control',
    phase: 'kubernetes',
    title: 'Deploying Thinkube Control',
    name: 'ansible/40_thinkube/core/thinkube-control/00_install.yaml'
  })

  console.log('Final playbook queue:', queue.map(p => `${p.id}: ${p.title}`))
  console.log('Total playbooks in queue:', queue.length)

  return queue
}

// Execute next playbook in queue
const executeNextPlaybook = async () => {
  console.log('executeNextPlaybook called, current index:', currentPlaybookIndex.value)

  if (currentPlaybookIndex.value >= playbookQueue.value.length) {
    console.log('All playbooks completed!')
    deploymentComplete.value = true
    updatePhaseStatuses()
    return
  }

  const playbook = playbookQueue.value[currentPlaybookIndex.value]
  console.log('Next playbook:', playbook.id, '-', playbook.title)
  currentPlaybook.value = playbook

  // Update current phase
  if (currentPhase.value !== playbook.phase) {
    currentPhase.value = playbook.phase
  }

  updatePhaseStatuses()

  // Wait for component to mount
  await nextTick()
  await new Promise(resolve => setTimeout(resolve, 100))

  // Start playbook execution
  if (currentPlaybookExecutor.value?.startExecution) {
    const sudoPassword = sessionStorage.getItem('sudoPassword')

    currentPlaybookExecutor.value.startExecution({
      environment: {
        ANSIBLE_BECOME_PASSWORD: sudoPassword,
        ANSIBLE_SSH_PASSWORD: sudoPassword
      },
      extra_vars: playbook.extraVars || {}
    })
  } else {
    console.error('PlaybookExecutor not ready')
  }
}

// Handle playbook completion
const handlePlaybookComplete = async (result) => {
  console.log('Playbook complete:', currentPlaybook.value?.title, 'Result:', result.status)

  if (result.status === 'error' || result.status === 'failed' || result.status === 'cancelled') {
    deploymentError.value = `Playbook ${currentPlaybook.value.title} failed: ${result.message || 'Check the logs'}`
    return
  }

  // Success - clear any previous error
  deploymentError.value = ''

  // Increment completed counter
  completedPlaybooks.value++

  // Move to next playbook
  currentPlaybookIndex.value++

  console.log('Playbook succeeded, waiting for continue click...')
}

// Handle user clicking Continue
const handlePlaybookContinue = () => {
  console.log('User clicked Continue')
  currentPlaybook.value = null
  executeNextPlaybook()
}

// Test mode functions
const canContinue = computed(() => {
  return !currentPlaybook.value && !deploymentComplete.value && currentPlaybookIndex.value < playbookQueue.value.length
})

const runTestPlaybook = async () => {
  console.log('🧪 Running test playbook 18...')
  currentPlaybook.value = {
    id: 'test-18',
    title: 'Test Deployment (18)',
    name: 'ansible/40_thinkube/core/thinkube-control/18_test.yaml',
    phase: 'test'
  }
  await nextTick()

  const sudoPassword = sessionStorage.getItem('sudoPassword')
  currentPlaybookExecutor.value?.startExecution({
    environment: {
      ANSIBLE_BECOME_PASSWORD: sudoPassword,
      ANSIBLE_SSH_PASSWORD: sudoPassword
    }
  })
}

const runRollbackPlaybook = async () => {
  console.log('🔄 Running rollback playbook 19...')
  currentPlaybook.value = {
    id: 'rollback-19',
    title: 'Rollback Deployment (19)',
    name: 'ansible/40_thinkube/core/thinkube-control/19_rollback.yaml',
    phase: 'rollback'
  }
  await nextTick()

  const sudoPassword = sessionStorage.getItem('sudoPassword')
  currentPlaybookExecutor.value?.startExecution({
    environment: {
      ANSIBLE_BECOME_PASSWORD: sudoPassword,
      ANSIBLE_SSH_PASSWORD: sudoPassword
    }
  })
}

// Retry current playbook
const retryCurrentPlaybook = () => {
  deploymentError.value = ''

  if (currentPlaybookExecutor.value?.startExecution) {
    const sudoPassword = sessionStorage.getItem('sudoPassword')
    currentPlaybookExecutor.value.startExecution({
      environment: {
        ANSIBLE_BECOME_PASSWORD: sudoPassword,
        ANSIBLE_SSH_PASSWORD: sudoPassword
      },
      extra_vars: currentPlaybook.value?.extraVars || {}
    })
  }
}

// Reset deployment
const resetDeployment = () => {
  router.push('/configuration')
}

// Start deployment on mount
onMounted(async () => {
  console.log('Deploy component mounted - starting fresh deployment')

  // Check test mode
  testMode.value = await isTestMode()
  if (testMode.value) {
    console.log('🧪 Test mode enabled - manual playbook control')
  }

  // Build queue
  const queue = await buildPlaybookQueue()
  playbookQueue.value = queue
  totalPlaybooks.value = queue.length
  currentPlaybookIndex.value = 0
  completedPlaybooks.value = 0

  // Start deployment
  setTimeout(() => {
    executeNextPlaybook()
  }, 500)
})
</script>

<style scoped>
/* Custom styles for deployment view */
</style>
