// frontend/app/installation/page.tsx
/*
 * Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
 * SPDX-License-Identifier: Apache-2.0
 */

"use client"

import { useState, useEffect, useRef, useMemo } from "react"
import { useRouter } from "next/navigation"
import { TkCard, TkCardContent, TkCardHeader, TkCardTitle } from "thinkube-style/components/cards-data"
import { TkButton } from "thinkube-style/components/buttons-badges"
import { TkBadge } from "thinkube-style/components/buttons-badges"
import { TkProgress } from "thinkube-style/components/feedback"
import { TkCheckbox } from "thinkube-style/components/forms-inputs"
import { TkLabel } from "thinkube-style/components/forms-inputs"
import { TkPageWrapper } from "thinkube-style/components/utilities"
import { ChevronRight } from "lucide-react"
import { getAnsibleLogClassName, getAnsibleLogPrefix } from "@/lib/ansible-log-utils"

interface InstallationStatus {
  phase: 'idle' | 'starting' | 'running' | 'completed' | 'failed'
  progress: number
  current_task: string
  logs: string[]
  errors: string[]
}

export default function Installation() {
  const router = useRouter()

  // Check if we're in skip-config mode
  const skipConfigMode = typeof window !== 'undefined'
    ? sessionStorage.getItem('skipConfigMode') === 'true'
    : false

  const [status, setStatus] = useState<InstallationStatus>({
    phase: 'starting',
    progress: 0,
    current_task: 'Initializing installation...',
    logs: [],
    errors: []
  })

  const logContainerRef = useRef<HTMLDivElement>(null)
  const [autoScroll, setAutoScroll] = useState(true)
  const wsRef = useRef<WebSocket | null>(null)

  const isComplete = useMemo(
    () => status.phase === 'completed' || status.phase === 'failed',
    [status.phase]
  )

  const getPhaseClass = (phase: string) => {
    const classes: Record<string, string> = {
      idle: 'bg-muted text-muted-foreground',
      starting: 'bg-info text-info-foreground',
      running: 'bg-primary text-primary-foreground',
      completed: 'bg-success text-success-foreground',
      failed: 'bg-destructive text-destructive-foreground'
    }
    return classes[phase] || 'bg-muted text-muted-foreground'
  }

  const getLogPrefix = (log: string) => {
    // Determine prefix based on log content
    if (log.includes('ERROR') || log.includes('failed')) return '✗'
    if (log.includes('WARNING')) return '!'
    if (log.includes('INSTALLER_STATUS')) return '>'
    if (log.includes('✅') || log.includes('complete')) return '✓'
    return '$'
  }

  const getLogClass = (log: string) => {
    // Add color classes based on log content
    if (log.includes('ERROR') || log.includes('failed')) return 'text-destructive font-semibold'
    if (log.includes('WARNING')) return 'text-warning'
    if (log.includes('INSTALLER_STATUS')) return 'text-info'
    if (log.includes('✅') || log.includes('complete')) return 'text-success'
    return 'text-foreground'
  }

  const connectWebSocket = () => {
    // In Tauri, we need to connect directly to localhost:8000
    // Tauri v2 uses tauri: protocol
    const isTauri = typeof window !== 'undefined' && window.location.protocol === 'tauri:'

    // Determine WebSocket base URL
    let wsBase: string
    if (isTauri) {
      // Tauri app - always connect to localhost:8000
      wsBase = 'ws://localhost:8000'
    } else if (
      typeof window !== 'undefined' &&
      window.location.hostname === 'localhost' &&
      window.location.port === '5173'
    ) {
      // Development mode (Vite dev server)
      wsBase = 'ws://localhost:8000'
    } else {
      // Production web deployment
      wsBase = typeof window !== 'undefined'
        ? `${window.location.protocol === 'https:' ? 'wss:' : 'ws:'}//${window.location.host}`
        : 'ws://localhost:8000'
    }

    // Try /ws first, then /api/ws
    let wsUrl = `${wsBase}/ws`
    let retryWithApi = true

    const createConnection = (url: string) => {
      const ws = new WebSocket(url)
      wsRef.current = ws

      ws.onopen = () => {
        retryWithApi = false
      }

      ws.onmessage = (event) => {
        const data = JSON.parse(event.data)
        setStatus(data)
      }

      ws.onerror = (error) => {
        if (retryWithApi && url.endsWith('/ws')) {
          // Try /api/ws endpoint
          retryWithApi = false
          wsUrl = `${wsBase}/api/ws`
          createConnection(wsUrl)
        }
      }

      ws.onclose = () => {
        // Reconnect after 5 seconds if not complete
        if (!isComplete) {
          setTimeout(() => createConnection(wsUrl), 5000)
        }
      }
    }

    createConnection(wsUrl)
  }

  // Auto-scroll effect
  useEffect(() => {
    if (autoScroll && logContainerRef.current) {
      logContainerRef.current.scrollTop = logContainerRef.current.scrollHeight
    }
  }, [status.logs, autoScroll])

  const continueNext = () => {
    if (skipConfigMode) {
      router.push('/deploy')
    } else {
      router.push('/server-discovery')
    }
  }

  useEffect(() => {
    connectWebSocket()

    return () => {
      if (wsRef.current) {
        wsRef.current.close()
      }
    }
  }, [])

  return (
    <TkPageWrapper title="Installation Progress">
      {/* TkProgress Overview */}
      <TkCard className="mb-6">
        <TkCardContent className="pt-6">
          <div className="flex justify-between items-center mb-4">
            <div>
              <div className="flex items-center gap-3">
                <TkBadge className={getPhaseClass(status.phase)}>
                  {status.phase}
                </TkBadge>
                <span className="text-lg font-semibold">{status.current_task}</span>
              </div>
            </div>
            <div className="text-4xl font-bold text-primary">{status.progress}%</div>
          </div>

          <TkProgress value={status.progress} className="w-full" />
        </TkCardContent>
      </TkCard>

      {/* Installation Logs */}
      <TkCard>
        <TkCardContent className="pt-6">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-xl font-semibold">Installation Logs</h2>
            <div className="flex items-center gap-2">
              <TkCheckbox
                id="auto-scroll"
                checked={autoScroll}
                onCheckedChange={(checked: boolean) => setAutoScroll(checked)}
              />
              <TkLabel htmlFor="auto-scroll" className="text-xs cursor-pointer">
                Auto-scroll
              </TkLabel>
            </div>
          </div>

          <div
            ref={logContainerRef}
            className="h-96 overflow-y-auto p-4 bg-muted/30 rounded-lg font-mono text-xs"
          >
            {status.logs.length === 0 && (
              <div className="text-muted-foreground">
                <div className="flex items-start">
                  <span className="text-muted-foreground mr-2">$</span>
                  <code>Waiting for output...</code>
                </div>
              </div>
            )}
            {status.logs.map((log, index) => (
              <div key={index} className={`flex items-start ${getLogClass(log)}`}>
                <span className="text-muted-foreground mr-2">{getLogPrefix(log)}</span>
                <code>{log}</code>
              </div>
            ))}
            {status.errors.map((error, index) => (
              <div key={`error-${index}`} className="flex items-start text-destructive font-semibold">
                <span className="text-muted-foreground mr-2">!</span>
                <code>ERROR: {error}</code>
              </div>
            ))}
          </div>
        </TkCardContent>
      </TkCard>

      {/* Completion Actions */}
      {isComplete && (
        <div className="mt-6">
          {status.phase === 'failed' && (
            <div className="bg-destructive/10 border border-destructive text-destructive rounded-lg p-4 flex gap-3 mb-4">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-6 w-6 shrink-0"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z"
                />
              </svg>
              <span>Installation failed. Please check the logs for details.</span>
            </div>
          )}

          <div className="flex justify-end">
            <TkButton
              size="lg"
              className="gap-2"
              onClick={continueNext}
            >
              {skipConfigMode ? 'Continue to Deployment' : 'Continue to Server Discovery'}
              <ChevronRight className="w-5 h-5" />
            </TkButton>
          </div>
        </div>
      )}
    </TkPageWrapper>
  )
}

// frontend/src/views/Installation.vue
/*
 * Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
 * SPDX-License-Identifier: Apache-2.0
 */

<template>
  <div class="max-w-4xl mx-auto">
    <h1 class="text-3xl font-bold mb-6">Installation Progress</h1>
    
    <!-- Progress Overview -->
    <div class="card bg-base-100 shadow-xl mb-6">
      <div class="card-body">
        <div class="text-center mb-6">
          <div class="radial-progress text-primary" 
               :style="`--value:${status.progress}; --size:12rem; --thickness:1rem;`">
            <span class="text-4xl font-bold progress-text">{{ status.progress }}%</span>
          </div>
        </div>
        
        <div class="flex justify-center gap-2 mb-4">
          <div class="badge" :class="getPhaseClass(status.phase)">
            {{ status.phase }}
          </div>
        </div>
        
        <p class="text-center text-lg mb-4">{{ status.current_task }}</p>
        
        <progress class="progress progress-primary w-full" :value="status.progress" max="100"></progress>
      </div>
    </div>

    <!-- Installation Logs -->
    <div class="card bg-base-100 shadow-xl">
      <div class="card-body">
        <div class="flex items-center justify-between mb-4">
          <h2 class="card-title">Installation Logs</h2>
          <button 
            class="btn btn-ghost btn-sm btn-circle"
            @click="autoScroll = !autoScroll"
            :class="{ 'btn-active': autoScroll }"
          >
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" 
                    :d="autoScroll ? 'M19 14l-7 7m0 0l-7-7m7 7V3' : 'M5 10l7-7m0 0l7 7m-7-7v18'"></path>
            </svg>
          </button>
        </div>
        
        <div ref="logContainer" class="log-container bg-base-200 rounded-lg p-4 h-96 overflow-y-auto font-mono text-sm">
          <div v-for="(log, index) in status.logs" :key="index" class="mb-1">
            <span class="text-base-content text-opacity-60">{{ formatTime(new Date()) }}</span>
            <span class="ml-2">{{ log }}</span>
          </div>
          
          <div v-if="status.errors.length > 0" class="mt-4 border-t border-error pt-4">
            <div v-for="(error, index) in status.errors" :key="`error-${index}`" class="text-error mb-1">
              <span class="text-error text-opacity-60">{{ formatTime(new Date()) }}</span>
              <span class="ml-2">ERROR: {{ error }}</span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Completion Actions -->
    <div v-if="isComplete" class="mt-6">
      <div v-if="status.phase === 'failed'" class="alert alert-error mb-4">
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <span>Installation failed. Please check the logs for details.</span>
      </div>
      
      <button 
        class="btn btn-primary btn-block btn-lg gap-2"
        @click="continueNext"
      >
        {{ skipConfigMode ? 'Continue to Deployment' : 'Continue to Server Discovery' }}
        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
        </svg>
      </button>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted, watch, nextTick } from 'vue'
import { useRouter } from 'vue-router'

const router = useRouter()

// Check if we're in skip-config mode
const skipConfigMode = sessionStorage.getItem('skipConfigMode') === 'true'

const status = ref({
  phase: 'starting',
  progress: 0,
  current_task: 'Initializing installation...',
  logs: [],
  errors: []
})

const logContainer = ref(null)
const autoScroll = ref(true)
let ws = null

const isComplete = computed(() => 
  status.value.phase === 'completed' || status.value.phase === 'failed'
)

const getPhaseClass = (phase) => {
  const classes = {
    idle: 'badge-ghost',
    starting: 'badge-info',
    running: 'badge-primary',
    completed: 'badge-success',
    failed: 'badge-error'
  }
  return classes[phase] || 'badge-ghost'
}

const formatTime = (date) => {
  return date.toTimeString().split(' ')[0]
}

const connectWebSocket = () => {
  // In Tauri, we need to connect directly to localhost:8000
  // Tauri v2 uses tauri: protocol, not window.__TAURI__
  const isTauri = window.location.protocol === 'tauri:'

  // Determine WebSocket base URL
  let wsBase
  if (isTauri) {
    // Tauri app - always connect to localhost:8000
    wsBase = 'ws://localhost:8000'
  } else if (window.location.hostname === 'localhost' && window.location.port === '5173') {
    // Development mode (Vite dev server)
    wsBase = 'ws://localhost:8000'
  } else {
    // Production web deployment
    wsBase = `${window.location.protocol === 'https:' ? 'wss:' : 'ws:'}//${window.location.host}`
  }

  console.log('WebSocket base URL:', wsBase, 'isTauri:', isTauri)

  // Try /ws first, then /api/ws
  let wsUrl = `${wsBase}/ws`
  let retryWithApi = true
  
  const createConnection = (url) => {
    console.log('Connecting to WebSocket:', url)
    ws = new WebSocket(url)
    
    ws.onopen = () => {
      console.log('WebSocket connected successfully')
      retryWithApi = false
    }
    
    ws.onmessage = (event) => {
      console.log('WebSocket message received:', event.data)
      const data = JSON.parse(event.data)
      status.value = data
      console.log('Status updated:', status.value)
    }
    
    ws.onerror = (error) => {
      console.error('WebSocket error:', error)
      if (retryWithApi && url.endsWith('/ws')) {
        // Try /api/ws endpoint
        retryWithApi = false
        wsUrl = `${wsBase}/api/ws`
        createConnection(wsUrl)
      }
    }
    
    ws.onclose = () => {
      // Reconnect after 5 seconds if not complete
      if (!isComplete.value) {
        setTimeout(() => createConnection(wsUrl), 5000)
      }
    }
  }
  
  createConnection(wsUrl)
}

watch(() => status.value.logs.length, async () => {
  if (autoScroll.value && logContainer.value) {
    await nextTick()
    logContainer.value.scrollTop = logContainer.value.scrollHeight
  }
})

const continueNext = () => {
  if (skipConfigMode) {
    router.push('/deploy')
  } else {
    router.push('/server-discovery')
  }
}

onMounted(() => {
  connectWebSocket()
})

onUnmounted(() => {
  if (ws) {
    ws.close()
  }
})
</script>

<style scoped>
.progress-text {
  animation: fade-pulse 1.5s ease-in-out infinite;
}

@keyframes fade-pulse {
  0%, 100% {
    opacity: 1;
  }
  50% {
    opacity: 0.7;
  }
}

.log-container {
  font-family: 'Courier New', monospace;
}
</style>
